### ISSUE TITLE
Minimal example of universal route & render

### ISSUE THREAD

**Issue by ericelliott** [reactjs/react-router-redux#232]
I spent a couple solid days getting universal route & render working with `redux-simple-router`. For the legions of other people working on universal apps, I think it would be great to supply a minimal working example in the `examples` folder. =)

See also https://github.com/rackt/redux-simple-router/issues/231

I got this working in [universal-react-boilerplate](https://github.com/cloverfield-tools/universal-react-boilerplate/tree/262b3a4026147658218dd8e6a98c8a72a09e4cf2), but it needs a little tidying up if it's going to be used for a documentation example.

If you're looking at this for reference, please pay attention to the version, because in the future we'll strip this stuff out and replace it with [react-easy-universal](https://github.com/ericelliott/react-easy-universal), which basically wrangles all these other libs together and automates this process.

**Comment by timdorr** [comment]
Do you want to submit a PR? That would be most helpful :smile:

**Comment by ericelliott** [comment]
I would love to, but I'm afraid I already spent too much time on it, but I'll see if I can recruit somebody. =)

**Comment by siawyoung** [comment]
Hey @ericelliott, I'd love to help out. Where's this description you're referring to?

**Comment by timdorr** [comment]
@siawyoung He means in the initial message of this issue. The basic gist is to create a very simple example of a universally rendered application.

**Comment by ericelliott** [comment]
:+1:

**Comment by gaearon** [comment]
I’m happy to accept a PR adding react-router-redux to the `universal` example in Redux repo.
It’s fine if it has only one or two routes.

The only thing additional to server rendering I want to show there is preparing the store with async action by grabbing static `fetchData` or similar on the component. That’s a very common technique we should describe.

**Comment by svenanders** [comment]
I got some time to spare to work up a minimal example, so I'd be happy to do it. What data source is preferrable to use?

**Comment by ericelliott** [comment]
@svenanders Maybe a route already available in existing examples in one of these repos?

**Comment by justin808** [comment]
@ericelliott I've got an example with server rendering:

[shakacode/react-webpack-rails-tutorial](https://github.com/shakacode/react-webpack-rails-tutorial). react-router-redux including **Server Rendering** using [React on Rails](https://github.com/shakacode/react_on_rails/), live at [www.reactrails.com](http://www.reactrails.com/).

**Comment by xulien** [comment]
I just created a PR on redux repo
https://github.com/reactjs/redux/pull/1403

it's just a proposal awaiting remarks

**Comment by ivan-hilckov** [comment]
@xulien Great work! tnx

**Comment by abhijeetNmishra** [comment]
@ericelliott @gaearon i am using 
```javascript 
const reduxRouterMiddleware = syncHistory(browserHistory);
```

above middle works for client side rendering. But if try to use same store on server it doesnt work.

Any help !!

**Comment by mjrussell** [comment]
@abhijeetNmishra Not sure if your comment is related to the original issue, but you are running into the fact that browserHistory doesn't exist on the server and will be undefined. Use memory history if running on the server instead.

**Comment by abhijeetNmishra** [comment]
@mjrussell 
```javascript
if (!client) {
    reduxRouterMiddleware = syncHistory(memoryHistory);
  } else {
    reduxRouterMiddleware = syncHistory(browserHistory);
  }
```
above is also not working when i am trying to create redux store.

**Comment by timdorr** [comment]
I just realized this landed in master too: https://github.com/reactjs/react-router-redux/tree/master/examples/server

I think this satisfies the original issue.

@abhijeetNmishra Check out the 4.0.0 branch. It should work for SSR just fine.

**Comment by abhijeetNmishra** [comment]
@timdorr i am gettin error:
```bash
(0 , _reactRouterRedux.routerMiddleware) is not a function
```

also i don't find routerMiddleware to be exported from react-router-redux file.

am i missing something for this implementation.

**Comment by timdorr** [comment]
`npm install --save react-router-redux@next`

**Comment by ababba15** [comment]
Didn't work for me..
