### ISSUE TITLE
Location object on server render

### ISSUE THREAD

**Issue by mmahalwy** [reactjs/react-router-redux#270]
The location object in the store on server render always had the initial with pathname `/`. To fix, I was able to do this:

```
app.use((req, res, next) => {
  const client = new ApiClient(req);
  const history = useQueries(createHistory)();
  const store = createStore(getRoutes, history, client);
  match({ history, routes: getRoutes(), location: req.originalUrl }, (error, redirectLocation, renderProps) => {
    // This is hacky, but we need to let react-router-redux know that
    // we have matched a route and things have changed!
    store.dispatch({
      type: UPDATE_LOCATION,
      payload: renderProps.location
    });
...
```
although I still feel like it's hacky. Anyone found a better solution?

**Comment by timdorr** [comment]
Is this 3.0 or the 4.0 beta?

I haven't done any server rendering testing on the latter (nor any other version, for that matter), and I think it's actively bugged. I'm hoping to look at that soon so we can push out a release candidate. 

However, just looking at things, you're not syncing the history with the store at all. You should be doing that, although the API might be insufficient and discouraging you from doing so. We should be able to take in initialState in some way that accounts for the provided location when you're in the server context.

**Comment by mmahalwy** [comment]
The problem was my `createHistory` was coming from the history library and not react-router. Once I used the react-router one and called it with `req.originalUrl` all was fixed!
