### ISSUE TITLE
Questions on the new API for selectLocationState param

### ISSUE THREAD

**Issue by justin808** [reactjs/react-router-redux#273]
Given the below, it's not clear if I should be creating the `selectLocationState` function to return an object that contains the `locationBeforeTransitions`. Supposing I'm using immutable, it seems to make more sense to return the payload rather than an object containing the payload.

Per this code:
```
export default function syncHistoryWithStore(history, store, {
  selectLocationState = defaultSelectLocationState,
  adjustUrlOnReplay = true
} = {}) {
  
  // What does the store say about current location?
  const getLocationInStore = (useInitialIfEmpty) => {
    const locationState = selectLocationState(store.getState())
    return locationState.locationBeforeTransitions ||
      (useInitialIfEmpty ? initialLocation : undefined)
  }
```

And per this documentation:
```
What if I use Immutable.js with my Redux store?

When using a wrapper for your store's state, such as Immutable.js, you will need to change two things from the standard setup:

Provide your own reducer function that will receive actions of type LOCATION_CHANGE and return the payload merged into state.
Pass a selector to access the payload state via the selectLocationState option on syncHistoryWithStore.
These two hooks will allow you to store the state that this library uses in whatever format or wrapper you would like.
```

and per this reducer with Immutable:

```js
/**
 * This action type will be dispatched when your history
 * receives a location change.
 * Based on https://github.com/reactjs/react-router-redux/blob/v4.0.0-beta.1/src%2Freducer.js
 */
import Immutable from 'immutable';

export const LOCATION_CHANGE = '@@router/LOCATION_CHANGE';

const $$initialState = Immutable.fromJS({
  locationBeforeTransitions: null
});

/**
 * This reducer will update the state with the most recent location history
 * has transitioned to. This may not be in sync with the router, particularly
 * if you have asynchronously-loaded routes, so reading from and relying on
 * this state it is discouraged.
 */
export function routerReducer($$state = $$initialState, { type, payload }) {
  if (type === LOCATION_CHANGE) {
    return $$state.merge({
      locationBeforeTransitions: payload,
    });
  } else {
    return $$state;
  }
}
```

**Comment by timdorr** [comment]
Because you're using your own selector and reducer, you can store the location in state however you'd like, including both the mechanism of storage (Immutable.js in this case) and the shape of the data. As long as your selector is returning an object with the key `locationBeforeTransitions`, you're doing it correctly.

**Comment by justin808** [comment]
Thanks @timdorr! 

Is there any reason to use immutableJs for the reducer of the location? I'm using immutable for other purposes, and combineReducers to put them together.

**Comment by timdorr** [comment]
if you're using `combineReducers`, you don't have a fully immutable state, just an object with keys containing immutable objects. In that case, where everything is not exclusively immutable, it's fine to not override the built-in reducer and selector.

**Comment by justin808** [comment]
Thanks @timdorr! 

We've got a universal app running 4.0! https://github.com/shakacode/react-webpack-rails-tutorial/pull/224

As soon as I get a code review, I'll merge, and this will be live. I'll then submit a PR to your README.md.

Let me know:

* if you have any comments on my installation of react-router-redux 
* what would be a good simple feature to show users that we've got react-router-redux working (btw, you can see the events logging if you open the console once we deploy this to heroku).
