### ISSUE TITLE
Link from react-router or routeActions.push from react-redux-router ?

### ISSUE THREAD

**Issue by Tux1** [reactjs/react-router-redux#274]
Hi guys,

I use it and  I was wondering, should I use `Link` component from `react-router` or `routerActions.push` from `react-redux-router` to make a link ?

I don't know very well how those tools works, but it seems to be equivalent, isn't it ? 

Thanks for your very helpful work

**Comment by timdorr** [comment]
You should use the Link component. The normal router tools all work as expected.
