### ISSUE TITLE
LOCATION_CHANGE on state change

### ISSUE THREAD

**Issue by schickling** [reactjs/react-router-redux#286]
I'm building a new app based on [react-redux-starter-kit](https://github.com/davezuko/react-redux-starter-kit) and constantly get `@@router/LOCATION_CHANGE` after another state change has occurred.

Here is a snippet from the starter-kit:
```js
// Configure history for react-router
const browserHistory = useRouterHistory(createBrowserHistory)({
  basename: __BASENAME__
})
const history = syncHistoryWithStore(browserHistory, store, {
  selectLocationState: (state) => state.router
})
```

PS: I hope this issue belongs here, otherwise I will repost it to [react-redux-starter-kit](https://github.com/davezuko/react-redux-starter-kit)

**Comment by timdorr** [comment]
I would open this up on their repo. It may be specific to their combination of libraries.

**Comment by gaearon** [comment]
Might be a bug though: https://github.com/davezuko/react-redux-starter-kit/issues/568#issuecomment-184902708.

**Comment by timdorr** [comment]
Looks like the linked comment was removed :/

**Comment by gaearon** [comment]
Yeah, it was changed to “everything is fine, it was an issue in my app” and then got deleted. :-)
