### ISSUE TITLE
Deep nested components losing context (<select> element in particular)

### ISSUE THREAD

**Issue by LKay** [reactjs/react-router-redux#290]
### Description
After moving to `react-router-redux` from custom solution I am facing weird problem with `<select>` element in particular. I am using `redux` with React 

The problem happens when some async action is being dispatched inside `componentWillReceiveProps` or `componentWillUpdate` hooks which responding to `routing` state change. React allows dispatching actions and changing state inside this hooks not like `componentDidUpdate`, so it is recommended way to change the state before re-rendering (costly operation) takes place.

During this action for some reason `<select>` is being unmounted and removed from DOM but some internal React still seem attached to it. This results with throwing an error `TypeError: Cannot set property 'initialValue' of null. ` It might be related to the issue on the `react` GitHub [#5968](https://github.com/facebook/react/issues/5968).

The error is not being thrown when `dispatch` is called inside `componentDidUpdate` but it's better not to do it here due to costly re-render. It is only happening when comparing `routing` state, so if I listen to change (comparing) any other prop not related to `routing` or remove `routing` from `connect()` then it also works fine.

The error seems to be related to `react-router` as if I remove `<BugWrap>` from inside `<Route>` and move it as direct child of `<Provider>` the async action works fine, and not throwing any error.

### Reproduce
On first render everything is working fine. Then after clicking a button, which dispatcher router action the error appears.

```jsx
import React, { Component } from "react"
import { render } from "react-dom"
import { Router, Route, IndexRoute, browserHistory } from "react-router"
import { Provider } from "react-redux"
import { createStore, applyMiddleware, compose, combineReducers } from "redux"
import thunkMiddleware from "redux-thunk"
import { createSelector } from "reselect"
import { syncHistory } from "react-router-redux"
import { connect } from "react-redux"
import { routeReducer, routeActions } from "react-router-redux"

function fluxAction () {
    const fakeItems = ["foo", "bar"]
    return (dispatch) => {
        dispatch({ type : "bugAction" })
        setTimeout(() => dispatch({ type : "bugAction", items : fakeItems }), 500)
    }
}

const initialState = { items : [] }

function fluxReducer (state = initialState, action = {}) {
    if (action.type === "bugAction") {
        if (!action.items) {
            return Object.assign({}, state, { items : [] })
        }
        return Object.assign({}, state, { items : action.items })
    }
    return state
}

const reducer = combineReducers({
    routing : routeReducer,
    bug : fluxReducer
})

const reduxRouterMiddleware = syncHistory(browserHistory)

const store = compose(
    applyMiddleware(
        thunkMiddleware,
        reduxRouterMiddleware
    )
)(createStore)(reducer)

const storeState = createSelector([
    (state) => state.bug,
    (state) => state.routing
], (bug, routing) => ({ bug, routing }))

class Bug extends Component {

    componentDidMount () {
        this.props.dispatch(fluxAction())
    }

    // HERE COMES THE BUG!
    componentWillReceiveProps (props) {
        if (this.props.routing.location.search !== props.routing.location.search) {
            this.props.dispatch(fluxAction())
        }
    }

    renderItem (item) {
        return (
            <li key={item}>{item} <select><option>{item}</option></select></li>
        )
    }

    onClickAsync () {
        const params = { fake : Math.random() }
        const state = store.getState()
        const {
            routing
            } = state
        const location = routing.location
        const pathname = location.pathname
        const query = Object.assign({}, location.query, params)

        store.dispatch(routeActions.push({ pathname, query }))
    }

    render () {
        return (
            <div>
                <button onClick={ this.onClickAsync.bind(this) }>reload async</button>
                <ul>
                    { this.props.bug.items.map(this.renderItem.bind(this)) }
                </ul>
            </div>
        )
    }

}

Bug = connect(storeState)(Bug)

class BugWrap extends Component {

    render () {
        return (
            <div>
                <h1>Wrapper</h1>
                { this.props.children }
            </div>
        )
    }

}

class Root extends Component {

    render () {
        return (
            <Provider store={ store }>
                <Router history={ browserHistory }>
                    <Route component={ BugWrap }>
                        <Route path="/" component={ Bug } />
                    </Route>
                </Router>
            </Provider>
        )
    }

}

render(<Root />, document.getElementById("container"))
```

### Libs
Extract from `package.json`:

```json
"dependencies": {
    "history"                        : "~2.0.0",
    "react"                          : "~0.14.7",
    "react-dom"                      : "~0.14.7",
    "react-redux"                    : "~4.4.0",
    "react-router"                   : "~2.0.0",
    "react-router-redux"             : "~3.0.0",
    "redux"                          : "~3.3.1",
    "redux-thunk"                    : "~1.0.3",
    "reselect"                       : "~2.0.3"
}
```

**Comment by timdorr** [comment]
It's discouraged to read routing state in components. It's meant for use outside of React. Instead, since this is a route component, just read from the props provided by router. `this.props.location.search`

**Comment by browniefed** [comment]
@timdorr This has been suggested by @ryanflorence here https://gist.github.com/zackify/e57419e73d7c7ca79815
(I mean he's never been wrong ;) )

I have one case where I use the URL to hold all my state, when a select changes I change the URL, and subsequently do a route comparison to then fire an asyncAction to load data. Much like is being done up above.

I then run into a few invariant violations about DOM mutating, etc. Moving from `componentWillReceiveProps => componentDidUpdate` causes these things to not happen for fairly obvious reasons.

Is there a decent pattern for handling this? URL holds state and I need to hook into the changing of that to then dispatch actions that load data.

**Comment by browniefed** [comment]
AH just realized probably more appropriate would be navigation hooks?
