### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by mlarcher** [reactjs/react-router-redux#291]
When switching from "react-router-redux": "2.1.0" to "react-router-redux": "3.0.0", I get "Uncaught RangeError: Maximum call stack size exceeded", apparently coming from mapValues.js:14 (but sourcemaps might be wrong).
Changelog doesn't indicate any breaking changes, so I didn't expect to have to change anything in our code. Please let me know what additional information could help figure out what's going wrong.

**Comment by timdorr** [comment]
You might need to remove your node_modules directory and rerun npm install.

**Comment by kwelch** [comment]
I am also getting this error. I have cleared node_modules. I currently don't have anything have a key for either resolve or moduleDirectories (I have seen this as a fix from other sources). 
Here is my dep list:
```
    "react": "0.14.6",
    "react-dom": "0.14.6",
    "react-redux": "4.4.0",
    "react-router": "2.0.0",
    "react-router-redux": "3.0.0",
    "redux": "3.3.1"
```

**Comment by zackhall** [comment]
Also getting this. Trying to call dispatch(push('/page')) from an action creator causes this issue.
