### ISSUE TITLE
Dispatching route changes from async action creators

### ISSUE THREAD

**Issue by tomduncalf** [reactjs/react-router-redux#292]
I'm having problems dispatching a route change from an async action creator using `redux-thunk` (in this case, because I want to perform multiple actions for one action call).

My code looks like:
```
export function gotoReview() {
    return (dispatch) => {
        dispatch(setCompletedSignup(true))
        dispatch(routeActions.push('/review'))
    }
}
```

and in the calling code, I am doing `this.props.dispatch(gotoReview())`

I would expect this to navigate to `/review`, and indeed I can see the `TRANSITION` action get dispatched in the devtools, but nothing else happens (no errors in the console, but no navigation)

Am I doing this correctly? A similar thing worked with `redux-router`'s `pushState`.

Thanks,
Tom

**Comment by tomduncalf** [comment]
A little bit of debugging (console.log in the middleware) identified my problem: I was including the `react-router-redux` middleware before the `redux-thunk` middleware, so the thunk hadn't been executed by the time it reached the router middleware.

For the benefit of others, your store set up should look like:

```
    const finalCreateStore = compose(
        applyMiddleware(thunk),
        applyMiddleware(reduxRouterMiddleware),
    )(createStore)
```

rather than

```
    const finalCreateStore = compose(
        applyMiddleware(reduxRouterMiddleware),
        applyMiddleware(thunk),
    )(createStore)
```

**Comment by tomduncalf** [comment]
(Does that mean redux compose runs from left to right, like the opposite of functional composition? :))

**Comment by timdorr** [comment]
Nope, it's right to left: https://github.com/reactjs/redux/blob/master/src/compose.js

**Comment by timdorr** [comment]
By the way, `applyMiddleware` is variadic, so you don't need to compose together multiple middlewares.

**Comment by tomduncalf** [comment]
Interesting, that was something I got from a tutorial long ago, I will
update. Thanks!

**Comment by sgrund14** [comment]
Hey, I think I'm having a similar problem, although I'm not sure it's a problem with my middleware setup.

Calling the asynchronous action like this:
`export const fetchEvents = () => {
	return (dispatch, store) => {
		fetch(`${path}/events`)
		.then(data => {
				dispatch(push('/events'));
			}
		})
		.catch(err => {
			console.log(err);
		});
	};
};`

This will change the URL and trigger the @@router/LOCATION_CHANGE action.

My store is setup like this:

`const store = createStore(
	rootReducer,
	applyMiddleware(routerMiddleware(history), thunk)
);`

I tried reversing the order of the two middlewares here (though I don't think it should matter).

When I dispatch the push action from a non-asynchronous action, the rendering of the new route works fine. However, it is when I dispatch the push action from an asynchronous action that the location changes, but the proper component is not rendered.

Thanks!
