### ISSUE TITLE
Question: Is this actually tied to react-router?

### ISSUE THREAD

**Issue by tybro0103** [reactjs/react-router-redux#293]
It appears as though this library simply syncs location between redux and history. Is that the case? If not, why say that it's specifically for react-router?

I'm contemplating using this with a different router that uses the same history API. So far, it seems like that should be perfectly fine. Am I wrong about this?

**Comment by timdorr** [comment]
It's really only tied to it by name. We have one test that uses router, but it's really just an integration test. You can use any history implementation as long as it follows the same API spec.
