### ISSUE TITLE
listenForReplays() causes infinite loop

### ISSUE THREAD

**Issue by pigulla** [reactjs/react-router-redux#295]
Please take a look at my [skeleton](https://github.com/pigulla/babel-es6-react-redux-skeleton) for ES6/React/Redux projects. Everything works beautifully, except if I enable `listenForReplays` [here](https://github.com/pigulla/babel-es6-react-redux-skeleton/blob/master/frontend/src/app/store/Store.js#L27), the application goes into an infinite loop (I recommend setting a breakpoint in the callback or your browser will become unresponsive).

Any help is appreciated!

**Comment by Bartekus** [comment]
I can attest to this issue being present as I've been struggling to upgrade [meatier](https://github.com/mattkrick/meatier) and have faced exactly the situation.

**Comment by crossman** [comment]
I'm running into the same issue in my app. I traced it to the same line in my case (`reduxRouterMiddleware.listenForReplays(store, state => state.get("routing"))`).

**Comment by timdorr** [comment]
4.0.0 is out and completely changes things, so this shouldn't be a problem now :)
