### ISSUE TITLE
immutablejs instructions

### ISSUE THREAD

**Issue by jokeyrhyme** [reactjs/react-router-redux#301]
I'm working from https://github.com/davezuko/react-redux-starter-kit if that helps explain my context.

This is the custom reducer I needed:

```js
import Immutable from 'immutable';
import {
    LOCATION_CHANGE
} from 'react-router-redux';

let initialState;

initialState = Immutable.fromJS({
    locationBeforeTransitions: undefined
});

export default (state = initialState, action) => {
    if (action.type === LOCATION_CHANGE) {
        return state.merge({
            locationBeforeTransitions: action.payload
        });
    }

    return state;
};
```

I had to read the following to figure this out:

- https://github.com/reactjs/react-router-redux/issues/298

- https://github.com/reactjs/react-router-redux/blob/v4.0.0/src/reducer.js

Also, I had to set up a custom "selectLocationState" selector to get immutable store values to be fed to Router correctly:

```js
import createHistory from 'history/lib/createHashHistory';
// or: import createHistory from 'history/lib/createBrowserHistory';
import { useRouterHistory } from 'react-router';
import { syncHistoryWithStore } from 'react-router-redux';

const browserHistory = useRouterHistory(createHistory)({
  basename: __BASENAME__
});
const history = syncHistoryWithStore(browserHistory, store, {
  selectLocationState: (state) => state.get('router').toJS()
});

// pass above "history" to Router component as a prop
```

That's mentioned here:

- https://github.com/reactjs/react-router-redux#what-if-i-use-immutablejs-with-my-redux-store

**Comment by jokeyrhyme** [comment]
https://github.com/gajus/redux-immutable/issues/23

**Comment by jamesisaac** [comment]
Exactly what I needed, thanks.  Was just trying to figure this out myself but getting stuck because I'd forgotten the `.toJS()` in the custom `selectLocationState` imlementation.  The very outdated instructions in the https://github.com/gajus/redux-immutable readme (which comes up very high in Google) don't help.  Would be great to have this documented somewhere.

**Comment by timdorr** [comment]
This is already in the docs: https://github.com/reactjs/react-router-redux#what-if-i-use-immutablejs-with-my-redux-store

If you want to submit a PR with a better answer to that question, I'll happily merge it in :smile:

**Comment by gajus** [comment]
> The very outdated instructions in the https://github.com/gajus/redux-immutable readme (which comes up very high in Google) don't help.

Which part of documentation are you referring to? There is nothing outdated as far as I am aware.

**Comment by timdorr** [comment]
@gajus It looks like this section isn't updated for 4.0.0: https://github.com/gajus/redux-immutable#using-with-react-router-redux

**Comment by jamesisaac** [comment]
Yup, API has changed in a couple of places.  Compare with the snippet at the top of this thread.

**Comment by gajus** [comment]
> very outdated

Is not the expression to use when API has changed 1 day ago (relative to the time of the post).

**Comment by jamesisaac** [comment]
My bad, sorry - came across this project on the day of posting and wasn't looking at the dates, so didn't realise the current API was this recent.

**Comment by renanvalentin** [comment]
Thanks @jokeyrhyme !

**Comment by jokeyrhyme** [comment]
The `syncHistoryWithStore` part in my original post (up the top) results in a brand new JavaScript Object each time, so which means the whole Immutable state in Redux will be brand new every time it executes (which is very regularly, even when the user does nothing).

I'll be updating the OP with example code from here:
- https://github.com/reactjs/react-router-redux/issues/314#issuecomment-190678756

**Comment by sjparsons** [comment]
I just put together an example app demonstrating React Router + Redux + Immutable.js 
https://github.com/sjparsons/react-router-redux-immutable

**Comment by Kronuz** [comment]
The actual code for `createSelectLocationState` that fixes the issue is:

```javascript
const createSelectLocationState = () => {
	let prevRoutingState, prevRoutingStateJS;
	return (state) => {
		const routingState = state.get('routing');
		if (typeof prevRoutingState === 'undefined' || !prevRoutingState.equals(routingState)) {
			prevRoutingState = routingState;
			prevRoutingStateJS = routingState.toJS();
		}
		return prevRoutingStateJS;
	};
};


const history = syncHistoryWithStore(browserHistory, store, {
	selectLocationState: createSelectLocationState(),
});
```

Note `prevRoutingState.equals(routingState)` is used, instead of `prevRoutingState !== routingState`, to compare the immutable objects.

**Comment by couturecraigj** [comment]
This sorta fixed the issue... it seems to have impacted the goBack functionality from what I can tell.

**Comment by couturecraigj** [comment]
I think the issue is that it was contradicting what was stated in the documentation... using `locationBeforeTransitions`.  In that case it should have been 

```js
const createSelectLocationState = () => {
	let prevRoutingState, prevRoutingStateJS;
	return (state) => {
		const routingState = state.getIn(['routing','locationBeforeTransitions']);
		if (typeof prevRoutingState === 'undefined' || !prevRoutingState.equals(routingState)) {
			prevRoutingState = routingState;
			prevRoutingStateJS = routingState.toJS();
		}
		return prevRoutingStateJS;
	};
};


const history = syncHistoryWithStore(browserHistory, store, {
	selectLocationState: createSelectLocationState(),
});
```
difference being that you need to `getIn` to get the value of `locationBeforeTransitions` rather than just the `routing` state.

**Comment by eLn86** [comment]
hey guys, i followed all the instructions closely, my initial state is also immutable object, but i'm still getting the error "state.get/state.getIn is not a function", anyone can help?

Store.js
`
// EXTERNAL DEPENDENCIES
import { createStore, combineReducers, applyMiddleware } from 'redux'
import routerReducer from './routerReducer'

// LOCAL DEPENDENCIES
import stateReducer from 'store/rootReducer'
import { createEnvBasedMiddleware } from 'lib/env'

const middlewares = []
const composedMiddlewares = applyMiddleware(...middlewares)
const rootMiddleware = createEnvBasedMiddleware(composedMiddlewares)

const store = createStore(
  combineReducers({
    state: stateReducer,
    routing: routerReducer
  }),
  rootMiddleware
)

export default store
`

routerReducer.js
`
import { fromJS } from 'immutable'
import {
  LOCATION_CHANGE
} from 'react-router-redux'
import { createReducer } from 'redux-act'

let initialState

initialState = fromJS({
  locationBeforeTransitions: {}
})

export default createReducer({
  [LOCATION_CHANGE]: (state, payload) => state.merge({ locationBeforeTransitions: payload })
}, initialState)
`

routes.js
`
// EXTERNAL DEPENDENCIES
import React from 'react'
import { Router, Switch, Route } from 'react-router-dom'
import createBrowserHistory from 'history/createBrowserHistory'
import { syncHistoryWithStore } from 'react-router-redux'

// INTERNAL DEPENDENCIES
import App from './App'
import store from 'store/store'

const createSelectLocationState = () => {
  let prevRoutingState, prevRoutingStateJS
  return (state) => {
    const routingState = state.getIn(['routing', 'locationBeforeTransitions'])
    if (typeof prevRoutingState === 'undefined' || !prevRoutingState.equals(routingState)) {
      prevRoutingState = routingState
      prevRoutingStateJS = routingState.toJS()
    }
    return prevRoutingStateJS
  }
}

const customHistory = createBrowserHistory()
const history = syncHistoryWithStore(customHistory, store, {
  selectLocationState: createSelectLocationState()
})

export default () => {
  const extraProps = { backgroundColor: 'red' }
  return (
    <Router history={history}>
      <Switch>
        <Route exact path='/' component={App} />
        <Route path='/home' render={props => <App {...props} data={extraProps} />} />
      </Switch>
    </Router>
  )
}
`

**Comment by wzup** [comment]
@Kronuz 

> Uncaught TypeError: state.get is not a function

Where did you get `state.get`?
