### ISSUE TITLE
syncHistoryWithStore example for using enhancers with middleware?

### ISSUE THREAD

**Issue by tanepiper** [reactjs/react-router-redux#305]
Consider the following example:

```
import thunk from 'redux-thunk';
import {
  applyMiddleware,
  compose,
  createStore
} from 'redux';
import { browserHistory } from 'react-router';
import { syncHistory } from 'react-router-redux';

import { reducers } from './../reducers';

/**
 * Method to create stores based on a set of passed
 * reducers
 * @returns {*}
 */
export function configureStore(initialState = {}) {

  const reduxRouterMiddleware = syncHistory(browserHistory);

  const enhancer = compose(
    // Middleware you want to use in development:
    applyMiddleware(thunk, reduxRouterMiddleware),
    // Required! Enable Redux DevTools with the monitors you chose
    window.devToolsExtension ? window.devToolsExtension() : f => f
  );

  // Sync dispatched route actions to the history

  const store = createStore(reducers, initialState, enhancer);

  if (module.hot) {
    module.hot.accept('../reducers', () => {
      store.replaceReducer(require('./../reducers').default);
    });
  }
  return store;
}
```

With the `4.0.0` API, `syncHistoryWithStore` now needs the store to be created first, but in this case the enhancer needs to be created before the store, which needs the middleware created from `3.x.x` syncHistory method.

What would be the best way to upgrade this?

**Comment by timdorr** [comment]
Just add a `history` arg to your `configureStore` function. 
```js
export function configureStore(history, initialState = {}) {


  const enhancer = compose(
    // Middleware you want to use in development:
    applyMiddleware(
      thunk,
      routerMiddleware(history)
    ),
    // Required! Enable Redux DevTools with the monitors you chose
    window.devToolsExtension ? window.devToolsExtension() : f => f
  );

  // Sync dispatched route actions to the history

  const store = createStore(reducers, initialState, enhancer);

  if (module.hot) {
    module.hot.accept('../reducers', () => {
      store.replaceReducer(require('./../reducers').default);
    });
  }
  return store;
}

**Comment by tanepiper** [comment]
Hmm, tried that but I get the following:

`Uncaught Error: Expected the routing state to be available either as `state.routing` or as the custom expression you can specify as `selectLocationState` in the `syncHistoryWithStore()` options. Ensure you have added the `routerReducer` to your store's reducers via `combineReducers` or whatever method you use to isolate your reducers.`

How I've tried it with what you've suggested is the `index.js` of the app is this:

```
import 'babel-polyfill';

import React from 'react';
import ReactDOM from 'react-dom';
import { browserHistory } from 'react-router';
import { syncHistoryWithStore } from 'react-router-redux';

import Root from './containers/Root';
import configureStore from './store/configureStore';

const store = configureStore(browserHistory);
const history = syncHistoryWithStore(browserHistory, store);

// Custom history listener to do a redirect from a #/hash path
history.listen((location) => {
  const path = (/#(\/.*)$/.exec(location.hash) || [])[1];
  if (path) history.replace(path);
});

const rootElem = document.getElementById('root');
const rootNode = (<Root history={history} store={store} />);

ReactDOM.render(rootNode, rootElem);
```

The createStore method is essentially the same as you have above.  In `reducers/index.js` we have:

```
import { combineReducers } from 'redux';
import { routeReducer } from 'react-router-redux';

import {....}  // Other reducers in the app

export const reducers = combineReducers({
  ...  // other reducers
  routing: routeReducer
});
```

**Comment by tanepiper** [comment]
Never mind, fixed in the end

**Comment by txm** [comment]
How did you fix it?  I have the same since updating all packages in package.json

**Comment by txm** [comment]
bah s%routeReducer%routerReducer%

**Comment by sirichaij** [comment]
I found it. 'routeReducer' has been changed to 'routerReducer'

```
import { routerReducer } from 'react-router-redux';
export const reducers = combineReducers({
  ...  // other reducers
  routing: routerReducer
});
```

**Comment by iamcoolkranthi** [comment]
Hi ,

import axios from 'axios';

import { browserHistory } from 'react-router';
import {AUTH_USER} from './type';
import NavMenu from "../components/navigation/components/NavMenu"


const ROOT_URL = 'http://127.0.1:3011';

export function signinUser({email,password}){
	
	return function(dispatch){
		axios.post(`${ROOT_URL}/signin`,{email,password}).then(response=>{
			dispatch({type:AUTH_USER});
			console.log(response.data.userId.id+"lllll;;;;ll");
			
			localStorage.setItem('token',response.data.token);
			localStorage.setItem('username',response.data.userId.username);
			localStorage.setItem('authrole',response.data.userId.authRole);
			browserHistory.push('/#/dashboard/');
			
			
					    
		}).catch(()=>{
			console.log('this is error');
		});
	}
	
}

but browserHistory.push('/#/dashboard/'); url is not  redirecting

**Comment by iamcoolkranthi** [comment]
please help me on this
