### ISSUE TITLE
How to get replace from routeAction

### ISSUE THREAD

**Issue by AnuragSinghTomarr** [reactjs/react-router-redux#307]
hi i need to use replace instead of push so that that history is not recorded. Mine code is 
```js
import { routeActions } from 'react-router-redux';
@connect(
  state => ({
    loaded: state.commonFilterSec.loaded,
    loading: state.commonFilterSec.loading,
    secFilterData: state.commonFilterSec.data.main,
    bannerImage: state.commonFilterSec.data.main.bannerImg,
    bannerPath: state.commonFilterSec.data.main.bannerPath,
    imagePath: state.commonFilterSec.data.main.imagePath,
    redirectLink: state.commonFilterSec.data.main.redirectLink,
    // params: state.router.params,
    // urlParams: state.location.data,
    // flushLink: state.commonFilterSec.commonSecondaryFilter
  }), { pushState: routeActions.push, replaceState: routeActions.replace, loadSecondaryFilterData })
```
Inside mine render function I'm using this.props.replaceState. So is this the right way to do.Any help would be useful

**Comment by timdorr** [comment]
Yes, that is the correct usage. Make sure you are also setting up the middleware and reducer as well.

**Comment by AnuragSinghTomarr** [comment]
Middleware can you elaborate or give any reference how to setup middleware

**Comment by timdorr** [comment]
Please read the README in full: https://github.com/reactjs/react-router-redux#what-if-i-want-to-issue-navigation-events-via-redux-actions

**Comment by AnuragSinghTomarr** [comment]
routerMiddleware seems not to be present in version 3. I am trying to use 
`const __routerMiddleware = routerMiddleware(browserHistory);`
But it throws error. I am react-router-redux version ^3.0.0

**Comment by timdorr** [comment]
Then read the 3.0 docs: https://github.com/reactjs/react-router-redux/tree/3.0.x
