### ISSUE TITLE
createMemoryHistory req.path/req.url in SSR example

### ISSUE THREAD

**Issue by landabaso** [reactjs/react-router-redux#308]
First of all let me thank you for the work done!

I'm following the SSR example here:
https://github.com/reactjs/react-router-redux/blob/master/examples/server/server.js

I believe that:
`const memoryHistory = createMemoryHistory(req.path)
`
should be:

`const memoryHistory = createMemoryHistory(req.url)
`
(line 39)

I guess it does not matter in the 'SSR' example since your routes are "/foo" and "/bar" but I believe it would be better to use req.url for those of us who are learning.

If req.path has to be used for some other reason, I'd be great some sort of quick explanation. Thanks!

**Comment by Furizaa** [comment]
I think you are right. I stumbled upon the same line. With `req.path` query parameters get ignored.
