### ISSUE TITLE
Uncaught SecurityError: Failed to execute 'replaceState' on 'History': 

### ISSUE THREAD

**Issue by transtone** [reactjs/react-router-redux#311]
A history state object with URL 'file:///D:/code/react-router-redux-example/index.html' cannot be created in a document with origin 'null'.

after update to react-router-redux-3.x, when open the index.html file localely, it not work. I must use a web server and open url like 'http://localhost:3000' , it works fine.
but with react-router-redux-2.x, no need to start a npm server.

**Comment by timdorr** [comment]
If you're using 3.0, there were no changes like this. You're probably trying to use a `browserHistory` with a local file. Just start up a simple web server to handle your code. You'll be using a real server in production anyways.

**Comment by transtone** [comment]
I just want a static website run with a jwt server , so I realy care about this. I'll have a try with ```browserHistory```.

**Comment by timdorr** [comment]
`browserHistory` will not work with local files. You have to use `hashHistory`.

**Comment by transtone** [comment]
I do use hasHistory, and it show me the bug.
