### ISSUE TITLE
Issue when trying to spread reducers

### ISSUE THREAD

**Issue by rasmuswoelk** [reactjs/react-router-redux#312]
Hi!

I'm quite new to React and Redux but I'm already loving it.

I'm having a problem when trying to set up react-router-redux. In the tutorial you spread the reducers with the ES6 spread feature:

```
	const store = createStore(
	  combineReducers({
	    ...reducers,
	    routing: routerReducer
	  })
	) 
```

When I run browserify I get the "Unexpected token" error. It should get compiled properly because it works when I try to copy in other examples.

My reducer file:

```
export default function user(state = {
	  firstname: 'Rasmus',
	  lastname: 'Andersen',
	}, action) {
	  switch (action.type) {
	    case UPDATE_USER:
	      return Object.assign({}, state, {
	        firstname: 'Carl'
	      })
	    default:
	      return state
	  }
	}
```

When I console.log reducers it returns undefined - is this normal?

Does anyone have suggestions for this?

Thanks!

**Comment by timdorr** [comment]
I assume you're transpiling things with Babel correctly?

I would make sure you're importing your `reducers` variable correctly.

**Comment by rasmuswoelk** [comment]
Thanks for the reply. I'm pretty sture I was importing the reducers correctly and babel must be running since a test with another spread function worked fine.

I must go back and try again. I might comment again here if I dont manage to get it to work.

**Comment by framerate** [comment]
@timdorr I am seeing a very similar problem

> I would make sure you're importing your reducers variable correctly.

Can you be more specific?

With two reducers `one: {a, b, c}, two: {x, y, z}`I can use `combineReducers({one, two})` with reducers to end up with a store that looks like:

```
{ 
   one: {a, b, c},
   two: {x, y, z}
}
```

But if I try `combineReducers({...one, two});` I end up with: 

```
{ 
   two: {x, y, z}
}
```

apparently where I would *expect*

```
{ 
   a, 
   b,
   c,
   two: {x, y, z}
}
```

**Comment by rasmuswoelk** [comment]
I am no longer experiencing this problem. I'm 99% sure that is was my babel presets that was wrong. I think you need stage-0 or stage-1 to be able to use the spread funktion.

**Comment by kwnccc** [comment]
@framerate Did you find any solution on the needed behaviour? I'm trying to do the same, but I'm not sure if should use `combineReducers` differently. Spreading the reducer `...one` it's not valid, since `one` is a function (as reducer), which makes sense not to work properly. What you actually need here is to spread the returned state of the reducer instead, but I'm not quite sure how to approach this behaviour.

**Comment by framerate** [comment]
@kwnccc I ended up separating my state into something more like:

```state = { 
    game,
    UI,
    logs
};```

with each being their own reducer and my headaches seemed to go away, even though it wasn't what I originally wanted.
