### ISSUE TITLE
Update README.md to show 4.0.0 API

### ISSUE THREAD

**Issue by r24y** [reactjs/react-router-redux#315]
The documentation demonstrates how to use the 2.0.0 API (and states so), but does not demonstrate how the 4.0.0 API works.

**Comment by r24y** [comment]
Ah, I see that the API is the same. I'll submit a PR soon so someone reading it isn't puzzled as to why the documentation only covers 2.0.

**Comment by timdorr** [comment]
I think you're mistaking this library for react-router. Router is at 2.0. This library (react-router-redux) is at 4.0.

**Comment by r24y** [comment]
Wow, that's embarrassing :flushed: my mistake! Thanks for pointing it out to me.
