### ISSUE TITLE
Url is stacking when using store.dispatch(push('todos'));

### ISSUE THREAD

**Issue by igorpreston** [reactjs/react-router-redux#316]
Hello, I am using redux actions to navigate between routes in my app, so that I came up with this in redux action being dispatched when I click on link the app:
```
store.dispatch(push('todos'));
```
The problem is that if I click several times on the same link or even another link, browser url becomes a mess: **todos/todos/todos**. When I click on **events** link, url changes to: **todos/todos/todos/events**. It seems like it preserves all previous pushes in url string.

What should I do about it?

**Comment by timdorr** [comment]
You should be using absolute URLs. 
```js
store.dispatch(push('/todos'));
```
