### ISSUE TITLE
Changing/creating synonym for library in SO

### ISSUE THREAD

**Issue by zekedroid** [reactjs/react-router-redux#317]
More of a discussion than an issue but any chance we could change the name of the label on stackoverflow or create a synonym? It threw me off for a while since I tried following the tag but it was set for `redux-simple-router`. I'd suggest the synonym myself but I don't have enough reputation. If it makes sense to make the change, maybe someone discussing can make the tag change.

[Synonyms page](http://stackoverflow.com/tags/redux-simple-router/synonyms)

**Comment by timdorr** [comment]
I don't have enough clout to make it happen. Anyone able to help out?

**Comment by timdorr** [comment]
The synonym is unlikely unless someone with a looot of karma helps out. Instead, @jeremybanks went through and retagged all the existing questions. Problem solved!

**Comment by zekedroid** [comment]
Hahaha, perfect. Thanks :D
