### ISSUE TITLE
routerMiddleware history

### ISSUE THREAD

**Issue by tj** [reactjs/react-router-redux#318]
does this need to be the same one returned from `syncHistoryWithStore()` or ? The docs are a little confusing

**Comment by tj** [comment]
ah nvm works with browserHistory so I guess not. As someone who hasn't used react-router on its own, it's not clear how to use this for "regular" links, can we still use Link etc, or do we have to use the middleware.

**Comment by timdorr** [comment]
`syncHistoryWithStore` returns an enhanced history object, which is used for keeping sync during store time travel. 

The middleware and action creator stuff is really it's own thing now. You don't have to use it if you don't want to. But if you do, you can [use an `onClick` handler](https://github.com/reactjs/react-router-redux/blob/master/examples/basic/components/App.js#L17) to run links through Redux as actions.
