### ISSUE TITLE
onEnter after replace

### ISSUE THREAD

**Issue by eMerzh** [reactjs/react-router-redux#320]
It seems that if you do a replace or a push of an url,
the "onEnter" callback of the component is not called.

is it normal?

**Comment by timdorr** [comment]
That is a react-router issue. It doesn't call `onEnter` if the location remains in the same part of the route tree. E.g., you go from /users/1 to /users/2, or even to /users.

**Comment by xdvarpunen** [comment]
Any solution for this or link where is stated this problem?
