### ISSUE TITLE
replace using fully qualified url

### ISSUE THREAD

**Issue by khankuan** [reactjs/react-router-redux#330]
Hey! I've gotten an error: 
`browser.js:49 Warning: A path must be pathname + search + hash only, not a fully qualified URL like "http://localhost:3000"`

when using
```
dispatch(replace({
  pathname: 'http://localhost:3000'
}));
```

The redirect works on server side rendering but gotten the error msg above on client side. Any ideas what is causing it?

This one fails on both server and client: 
```
dispatch(replace('http://localhost:3000'))
```

**Comment by timdorr** [comment]
You shouldn't use the full URL for a `replace`/`push`.

**Comment by khankuan** [comment]
Hmm, the use case is for urls that are on a different domain. My current solution is basically:
```
if (typeof window !== 'undefined' && url.indexOf('http') > -1){
  window.location = url
} else {
  push(url)
}
```

That is kind of ugly because `push` works perfectly on server side rendering.

**Comment by timdorr** [comment]
Well, regardless, this isn't the repo for it. You should be posting on history or router's repo, and more likely on StackOverflow or Reactiflux.

**Comment by khankuan** [comment]
Ok, thank you!

**Comment by khankuan** [comment]
Anyway, I dont think this functionality belongs to the history library as well. Will probably solve it by writing a middleware the intercept `react-router-redux` middleware and do the redirect. Thanks.
