### ISSUE TITLE
Uncaught TypeError: Cannot read property 'push' of undefined

### ISSUE THREAD

**Issue by fuyi** [reactjs/react-router-redux#331]
I have upgraded react-router-redux package from 3.0.0 to 4.0.0

In my code, I need to use push method defined in routeActions to manually change routes

```
import { routeActions } from 'react-router-redux';

...

routeActions.push('/');
```

This reports error:

```
Uncaught TypeError: Cannot read property 'push' of undefined
```

**Comment by fuyi** [comment]
I figure it out that the name  has changed from routeActions to routerActions.

Should this be documented somewhere?

**Comment by mmahalwy** [comment]
@fuyi thanks for finding that! it was driving me nuts!

**Comment by mistre83** [comment]
I did changed to routerActions but i'm getting too  Cannot read property 'push' of undefined

```
import { routerActions } from 'react-router-redux'

function mapDispatchToProps(dispatch) {
    return {
        ...bindActionCreators({
            routerActions,
            loadSystems
        }, dispatch)
    }
}

export default connect(mapStateToProps, mapDispatchToProps)(Dashboard);

```

**Comment by mmahalwy** [comment]
`...routerActions,`
