### ISSUE TITLE
Not compatible with IE8 (ES3)

### ISSUE THREAD

**Issue by ctumolosus** [reactjs/react-router-redux#332]
The output in `./lib` is not compatible with IE8 due to usage of unquoted reserved keys (e.g. `export.default` should be `export['default']`). I forked the repo hoping that I could fix it using `babel-plugin-transform-es3-property-literals` and `babel-plugin-transform-es3-member-expression-literals` but as this thread indicates it doesn't solve the issue: https://phabricator.babeljs.io/T2817. It seems using `es3ify` is a workaround for now. I can transform your package at build time on my end, but I wonder if it's something that should be addressed here instead.

**Comment by SimenB** [comment]
The bugs in the es3 transforms are fixed

**Comment by ctumolosus** [comment]
Hi @SimenB, I'm still experiencing issues with the plugins. I have committed my changes to https://github.com/ctumolosus/react-router-redux if you would like to take a look.

The issue is that [`syncHistoryWithStore`](https://github.com/ctumolosus/react-router-redux/blob/master/src/sync.js#L17) is transformed to `exports.default = syncHistoryWithStore;` instead of `exports['default'] = syncHistoryWithStore;`.

**Comment by timdorr** [comment]
I should just be able to rebuild against a newer Babel and we'll be all good. I'll try to get to that soon.

**Comment by ctumolosus** [comment]
@timdorr I bumped babel and created a PR for your review. The issue was fixed in their latest release.
