### ISSUE TITLE
Get pathname using Immutable. 

### ISSUE THREAD

**Issue by amorino** [reactjs/react-router-redux#333]
I read: https://github.com/reactjs/react-router-redux/issues/314 to get react-router-redux to work in immutable. However, using `state.get('route')` in mapStateToProps returns me the initial and the route state. How is it possible to get only the route state?

I think Immutable integration need a little more documentation. Thanks!

**Comment by timdorr** [comment]
You should use just the built-in Router props. mSTP is a hack with some rough edges, so I wouldn't recommend that approach. We should remove it from the docs.
