### ISSUE TITLE
push action seems to be dispatched, but the url doesn't change.

### ISSUE THREAD

**Issue by Kaijun** [reactjs/react-router-redux#335]
I'm using [redux-promise](https://github.com/acdlite/redux-promise) in my project

in my View, i mapped dispatch of push action and loginAction in the props, then trigger push after the user successfully logged in .
```
loginHandler = (e) => {
...
    this.props.userActions.login(data).then(() => {
      this.props.push('/courses')
    })
  }
...
```
and i also checked the logger, it showed that the push action was successfully dispatched.(according to the data in payload)
```
{
	"type": "@@router/CALL_HISTORY_METHOD",
	"payload": {
		"method": "push",
		"args": ["/courses"]
	}
}
```

but the url didn't change.

What went wrong?

**Comment by timdorr** [comment]
You probably have something connected wrong. Just use `this.context.router.push`.

**Comment by Robinnnnn** [comment]
I'm seeing the exact same error in my actions. v3.8.0

```
import { routerActions } from 'react-router-redux';
const loginUser = () => {
    return (dispatch) => {
        dispatch(routerActions.push(redirect))
    }
}

OR

import { push } from 'react-router-redux';
const loginUser = () => {
    return (dispatch) => {
        dispatch(push(redirect))
    }
}
```
Both of these methods, which I assume are equivalent, yield the following:

```
{
    "type": "@@router/CALL_HISTORY_METHOD",
    "payload": {
        "method": "push",
        "args": ["/"]
    }
}
```

Any idea what the reason could be?

**Comment by Robinnnnn** [comment]
Here's some more info about how my app is set up:

```
// reducer
export default combineReducers({
	auth,
	projectLibrary,
	user,
	survey,
	tracking,
	form: formReducer,
	browser: responsiveStateReducer,
	routing: routerReducer // relevant line
});

// store
export const configureStore = (initialState) => {
	const logger = createLogger({ predicate });
	const createStoreWithMiddleware = applyMiddleware(
		thunk,
		logger,
	)(createStore)
	const store = createStoreWithMiddleware(rootReducer, initialState); // relevant line
	return store;
}

// router
export default class Root extends React.Component {
	render() {
		const { store } = this.props;
		const history = syncHistoryWithStore(browserHistory, store) // relevant line

		const requireAuthentication = (nextState, replace) => {
			store.dispatch(requireAuth(nextState, replace, store));
		}

		return (
			<div>
			  <Provider store={store}>
			    <Router history={history}>
			      <Route   path="/" 				component={App}			 		  >
			        <IndexRoute   			    component={Landing} 		 />
			      	<Route path="downloads" component={Downloads} 	onEnter={requireAuthentication}/>
			        	<IndexRoute 					component={Project}/>
			        </Route>
			        <Redirect from="*" to="nomatch"/>
			      </Route>
			    </Router>
			  </Provider>
			</div>
		)
	}
}
```

**Comment by mjrussell** [comment]
@Robinnnnn make sure you read the README - https://github.com/reactjs/react-router-redux#what-if-i-want-to-issue-navigation-events-via-redux-actions

**Comment by Robinnnnn** [comment]
Thanks for the tip @mjrussell. I've followed the README but to no avail, here's my updated store:

```
// store
export const configureStore = (initialState) => {
    const browserMiddleware = routerMiddleware(browserHistory); // Added this line
    const logger = createLogger({ predicate });

    const createStoreWithMiddleware = applyMiddleware(
        thunk,
        logger,
        browserMiddleware // Also added this line!
    )(createStore)
    const store = createStoreWithMiddleware(rootReducer, initialState); // relevant line
    return store;
}
```

I feel like this structure follows [the one described in the docs](https://github.com/reactjs/react-router-redux#what-if-i-want-to-issue-navigation-events-via-redux-actions) very clearly. I'm importing both `browserHistory` and `routerMiddleware` from react-router-redux. 

Whenever I attempt to `push` to another route, I see the `CALL_HISTORY_METHOD` triggering but immediately get an error: cannot read property 'push' of undefined.

<img width="635" alt="screen shot 2016-03-22 at 10 25 10 pm" src="https://cloud.githubusercontent.com/assets/12162433/13973820/0934103a-f07d-11e5-9b77-f3f1a9acc7bf.png">

**Comment by Robinnnnn** [comment]
I figured out the issue. I was wrongly importing `browserHistory` from `react-router-redux` when it really should've been coming from `react-router`. 

Sorry for the inconvenience, everyone!
