### ISSUE TITLE
Number of backwards or forwards steps not dispatched

### ISSUE THREAD

**Issue by rybon** [reactjs/react-router-redux#337]
When using for example `store.dispatch(go(-3))` the number `-3` is not part of the resulting `LOCATION_CHANGE` action that gets dispatched to the reducers. Could that number be added to the payload?
The use case is that I need to unwind or rewind a stack structure in one of my reducers based on this number. I can't find it on the `LOCATION_CHANGE` payload though and need to dispatch another action just to get that number, which is undesirable.

**Comment by timdorr** [comment]
Yes, [it is included](https://github.com/reactjs/react-router-redux/blob/master/src/actions.js#L9-L12). Check action.payload.args.

**Comment by rybon** [comment]
Nope, the action `CALL_HISTORY_METHOD` is not dispatched to the reducers. It is only intercepted by the middleware.

**Comment by timdorr** [comment]
Yes, the default middleware will swallow that action. You can make your own middleware that doesn't do this. [The provided middleware is very simple](https://github.com/reactjs/react-router-redux/blob/master/src/middleware.js). Just add `return next(action)` at the end.

**Comment by rybon** [comment]
Fair enough, I'll try that. But wouldn't it make sense to add the number to the `LOCATION_CHANGE` payload as well?

**Comment by timdorr** [comment]
No, the `LOCATION_CHANGE` action only occurs on `history.listen` callbacks. We don't know what is the source of those location changes.
