### ISSUE TITLE
Can't set `nextPathname` in location descriptor for `replace()` method on `onEnter()`

### ISSUE THREAD

**Issue by SupremeTechnopriest** [reactjs/react-router-redux#338]
This used to work just fine.  Then someone went and changed the api without documenting any breaking changes.   Extremely frustrating.  

I have a route checking for authentication `onEnter`:

```javascript
const requireAuth = (nextState, replace) => {
	
	console.log(nextState.location);

	if(!isLoggedIn()) {
		replace({ pathname: '/login', nextPathname: nextState.location.pathname });
	}

	if(isLoggedIn() && !userHasAccess()) {
		replace({ pathname: '/forgot-password', nextPathname: nextState.location.pathname });
		Store.dispatch(updateIceCream('error', 'You must verify your account.  Enter your email above if you need a new code.'));
	}

}
```

And at the end of my login action creator:

```javascript
 let state = getState(),
      routeState = state.route.location.state;

dispatch(replace(routeState ? routeState.nextPathname : '/'));

```

First thing I'm noticing is that it's no longer `getState().route.location` it's now `getState().route.locationBeforeTransitions`.  This is not documented anywhere.   

Second thing I'm noticing is that `getState.route.locationBeforeTransitions.state` is always null.  Where am I supposed to pick up the `nextPathname` prop I'm attempting to supply to the `replace` methods `location` argument?

**Comment by SupremeTechnopriest** [comment]
Is it a leftpad bug? :laughing:

**Comment by timdorr** [comment]
> First thing I'm noticing is that it's no longer getState().route.location it's now getState().route.locationBeforeTransitions. This is not documented anywhere.

Because that state isn't reliable to listen to (as the name implies, it's not the fully-resolved location state). Instead, use the history singleton to read from.

> Where am I supposed to pick up the nextPathname prop I'm attempting to supply to the replace methods location argument?

`browserHistory.listen(location => currentLocation = location)` This is a synchronous call.
