### ISSUE TITLE
@@router/LOCATION_CHANGED raised on first page load with server-side rendering, should it be?

### ISSUE THREAD

**Issue by pauldotknopf** [reactjs/react-router-redux#340]
![Actions...](http://i.imgur.com/2YYkgiG.png)

I am rendering my initial page on the server. The route being displayed is already correct.

I would expect the server to provide the initial store state with the ```locationBeforeTransitions``` populated with the correct values from the server.

I would also expect then the client to not fire the ```@@router/LOCATION_CHANGE``` action on client page load, since ```locationBeforeTransitions``` is populated correct from the server.

The reason why I bring this up is because I am providing some initial state via the store from the server to the client, and I want this data to only be available on initial page load. When the user navigates to another page (```@@router/LOCATION_CHANGE```), I clear out the values provided by the server. The problem is that I do not know if the ```@@router/LOCATION_CHANGE``` is a result of the initial client-side page load, or a result of an actual navigation.

I supposed I could keep track of the number of times ```@@router/LOCATION_CHANGE``` is fired, and if it is fired twice, then clear the data.

**Comment by pauldotknopf** [comment]
I managed to work around this initial ```@@router/LOCATION_CHANGE``` action by the following code...

```js
import { LOCATION_CHANGE } from 'react-router-redux';

export default function reducer(state = { $internal: false }, action = {}) {
  switch (action.type) {
    case '_HYDRATE_VIEWBAG':
      return {
        ...state,
        ...action.viewBag
      };
    case LOCATION_CHANGE:
      if (state.$internal) return { $internal: true };
      return {
        ...state,
        $internal: true,
        ...action.viewBag
      };
    default:
      return state;
  }
}

```

**Comment by timdorr** [comment]
Simply set `adjustUrlOnReplay` to false.
