### ISSUE TITLE
Saving additional data in locationBeforeTransitions object.

### ISSUE THREAD

**Issue by pauldotknopf** [reactjs/react-router-redux#341]
Is it possible to store some additional data in the ```locationBeforeTransitions``` object?
I have some data that I want to continue to display the the user uses the back button, but if they navigate to the page normally, there will be client-side network request to load that data again.

**Comment by timdorr** [comment]
It's not recommended that you read from or deal with that bit of state. It's kept around for Dev Tools integration. As it's name applies, it may not represent the final location state after transitions have run and have, possibly, altered the location in some way. 

If you need to load state, you should have some means for doing that directly through Redux. This library doesn't have anything to do with that.

**Comment by divined** [comment]
But if i need this?

i.e. i not use sqarch query in browser, but want it ti be handlen in GA.
I want to save sqarch query params in the locationBeforeTransitions object. Because it must be sunhronized with it path.

**Comment by divined** [comment]
i.e. i not use search query in browser, but want it to be handled in GA.
I want to save search query params in the locationBeforeTransitions object. Because it must be synchronized with it path.
