### ISSUE TITLE
npm start  error

### ISSUE THREAD

**Issue by yumenglong** [reactjs/react-router-redux#345]
G:\xampphtdocs\LFFworkSpace\A-new-React-flux-require\react-router-redux\examples\basic>npm start

> rrr-basic-example@0.0.0 start G:\xampphtdocs\LFFworkSpace\A-new-React-flux-require\react-router-redux\examples\basic
> webpack-dev-server --history-api-fallback --no-info --open

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:8080
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at Server._listen2 (net.js:1231:14)
    at listen (net.js:1267:10)
    at net.js:1376:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:63:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:82:10)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "G:\\program files\\nodejs\\node.exe" "G:\\program files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.4.0
npm ERR! npm  v2.14.20
npm ERR! code ELIFECYCLE
npm ERR! rrr-basic-example@0.0.0 start: `webpack-dev-server --history-api-fallback --no-info --open`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rrr-basic-example@0.0.0 start script 'webpack-dev-server --history-api-fallback --no-info --open'.
npm ERR! This is most likely a problem with the rrr-basic-example package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --history-api-fallback --no-info --open
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs rrr-basic-example
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls rrr-basic-example
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     G:\xampphtdocs\LFFworkSpace\A-new-React-flux-require\react-router-redux\examples\basic\npm-debug.log

**Comment by sabha** [comment]
Please share the fix , I am having the same issue.

```
Error: Cannot find module 'core-js/library/fn/get-iterator'
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.4.3
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE
npm ERR! rrr-server-example@0.0.0 start: `babel-node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rrr-server-example@0.0.0 start script 'babel-node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the rrr-server-example package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs rrr-server-example
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls rrr-server-example
npm ERR! There is likely additional logging output above.
```
