### ISSUE TITLE
Calling routerReducer() with no args crashes

### ISSUE THREAD

**Issue by mindjuice** [reactjs/react-router-redux#349]
If you call `routerReducer()` with no arguments to get back the initial state, it crashes with the following error:

`reducer.js: Uncaught TypeError: Cannot read property 'type' of undefined`

The generated code looks like this:

    function routerReducer() {
      var state = arguments.length <= 0 || arguments[0] === undefined ? initialState : arguments[0];
      var _ref = arguments[1];
      var type = _ref.type;       // <==== _ref is undefined here and _ref.type causes the error
      var payload = _ref.payload;
    
      if (type === LOCATION_CHANGE) {
        return _extends({}, state, { locationBeforeTransitions: payload });
      }

      return state;
    }

This can be fixed in the original code by adding a default parameter for the action parameter:

    export function routerReducer(state = initialState, { type, payload } = {}) {

It made me wonder though what the correct behavior of Babel should be here.  Should it provide safe destructuring or still leave that up to your code?  I checked Traceur though and it behaves the same way, so perhaps that's not part of the spec, but it seems dangerous.

**Comment by timdorr** [comment]
Babel is handling destructuring properly. nil/null/undefined handling is a normal problem with just about every weak typed language out there. Even when it's natively supported by the VM, it still means you're trying to access a property of undefined. I'm not sure what the spec says about that, but I imagine it handles it with an error as well.

**Comment by mindjuice** [comment]
Thanks for the merge.

I can understand the undefined handling in the normal case where you are writing the code to dereference explicitly, but with destructuring, that code is written behind the scenes and it's much easier to make a mistake IMO.  Oh well...guess I need to join TC39! :smile:

I tried reading the spec, but wow...not an easy doc to read, even just the sections on destructuring!

    http://www.ecma-international.org/ecma-262/6.0/

**Comment by mindjuice** [comment]
@timdorr Any idea when we can get a new release with this fix in it?

Thanks!

**Comment by timdorr** [comment]
I'll try to get something out tonight. For now, you can install straight from github.

**Comment by mindjuice** [comment]
Thanks!  Much appreciated Tim!
