### ISSUE TITLE
Using push/replace does not take into account the configured basename

### ISSUE THREAD

**Issue by CervantesVive** [reactjs/react-router-redux#352]
I have an app deployed at a sub-path within my site.

http://domain/myapp/

I use `useRouterHistory` from react-router so I can use `useBasename` enhancer.
https://github.com/reactjs/react-router/blob/master/docs/API.md#userouterhistorycreatehistory

When I use a react-router-redux action to navigate, the basename is not taken into account.
https://github.com/reactjs/react-router-redux#what-if-i-want-to-issue-navigation-events-via-redux-actions

The main issue is that when I use onEnter property on a route to potentially route elsewhere the react-router replace() call works taking the basename into account, but the state tree does not reflect the updated URL.

If I use the react-router-redux replace() then the navigation takes place but without taking into account the basename.

**Comment by timdorr** [comment]
Are you sure you have the same history instance? [We simply pass-thru the action to the appropriate history method](https://github.com/reactjs/react-router-redux/blob/master/src/middleware.js#L15), so as long as you have the right history instance, then you should be fine.

**Comment by CervantesVive** [comment]
Sorry, I was incorrectly using the browser-history off 'react-router' when initializing the syncHistory() when I should have been using the custom history() object that was created and passed into the router,

Consider this issue resolved.
