### ISSUE TITLE
create umd dist build - for webpack aliasing

### ISSUE THREAD

**Issue by tomgrooffer** [reactjs/react-router-redux#354]
this is useful when creating aliases to improve webpack

http://survivejs.com/webpack/developing-with-webpack/optimizing-development/

**Comment by timdorr** [comment]
If someone wants to submit a PR that adds UMD support, go right ahead. I don't know what's involved, so I'm not the expert on the subject.

**Comment by Dattaya** [comment]
> I'm not the expert on the subject.
Me neither, but I need that umd build, so I would like to ask someone knowledgeable to review the PR.
