### ISSUE TITLE
Allow apply logic to PUSH or REPLACE location

### ISSUE THREAD

**Issue by tbicr** [reactjs/react-router-redux#355]
It will help keep browser history clean and usable, when you have many not necessary location changes.

For example I have app with map where location updated to current map center (like on osm.org), I want avoid PUSH current map center changes to history and use REPLACE instead.

**Comment by timdorr** [comment]
I'm not sure what you're asking. [We have a `replace` action](https://github.com/reactjs/react-router-redux/blob/master/src/actions.js#L21) and you can call `history.replace` from your synced history.

**Comment by tbicr** [comment]
@timdorr I mean how it sync https://github.com/reactjs/react-router-redux/blob/master/src/sync.js#L59

**Comment by timdorr** [comment]
Just set `adjustUrlOnReplay` to false.

**Comment by tbicr** [comment]
In this case location not synchronized.
