### ISSUE TITLE
Lost state when directly type router link in url 

### ISSUE THREAD

**Issue by EasonWang01** [reactjs/react-router-redux#358]
Hi,

For example
```
  <Provider store={store} >
     <Router history={history}>
      <Route path="/" foo="bar" component={App}>
         <Route path="/as" component={TodoList}/>
         <Route path="/aas" component={TodoInput}/>
      </Route>
    </Router> 
  </Provider>
```
if I was in `http://localhost:3000/as` and type `http://localhost:3000/aas` in url 

the state will be initialize.

But if I'm using ` <Link to="/aas">Bar</Link>` it will not lost state,just works fine.

How to solve it?

Thanks for reply.

**Comment by timdorr** [comment]
You cannot. The browser is treating that as a new page and will navigate to it. The only way you can interact with the URL bar and keep state is with a hash history.

**Comment by jljorgenson18** [comment]
If you are referring to general redux state and not the history state, you may want to look into redux-localstorage if you want some persistence between refreshes.
