### ISSUE TITLE
Issuing navigation commands via reducer

### ISSUE THREAD

**Issue by thekevinscott** [reactjs/react-router-redux#360]
Hi,

I've got a multipage form-based application that performs validation after each request to determine which page to navigate to next.

I'm currently handling this logic in actions via thunks, so that it updates the data, then performs a validation, then based on the response in that validation, executes some if else logic, like:

```
export function createNewForm(data) {
  return function (dispatch) {
    return fetch('xxx', {
      ...
    }).then((response) => {
      dispatch(validateForm());
    }).catch((err) => {
      ...
    });
  };
}

export function validateForm() {
  return function (dispatch) {
    return fetch('xxx', {
      ...
    }).then((response) => {
      if (missing(response.someData)) {
         dispatch(push('/some-url'));
      } else if (missing(response.somData2)) {
         dispatch(push('/some-url'));
      }
    }).catch((err) => {
      ...
    });
  };
}
```

This works, but it feels like the reducer should handle this if / else logic. Right?

So my questions are:

1) Should a reducer, in fact, be handling this? Or is an action the right place to store this logic?
2) If a reducer should be handling this, is there a way with react-router-redux to catch these actions?

**Comment by scottlabs** [comment]
The way I've gone about implementing this is by implementing a bit of middleware that listens for a particular property on the state (`routing.nextUrl`) and based on this dispatches the navigation command and clears that bit of state.

Still feels a bit hacky but it does allow me to dictate desired routes in my reducer. I'm also not sure how this pattern will scale. I'd love feedback from folks who have dealt with this problem in larger codebases.

**Comment by timdorr** [comment]
Reducers must be pure functions, so dispatching or causing other side effects doesn't work. You can handle this via a subscriber to the store that can subscribe when you mount your component and unsubscribes on unmounting.
