### ISSUE TITLE
Return something meaningful from dispatch in the middleware

### ISSUE THREAD

**Issue by idolize** [reactjs/react-router-redux#368]
Right now the [middleware will return `undefined`](https://github.com/reactjs/react-router-redux/blob/master/src/middleware.js#L15) when it calls into `history`. What I'd really like is instead to get some kind of description of what happened (even just a `true`/`false` depending on if the transition succeeded would be helpful).

My use case is that I have a "confirm changes" dialog that I trigger when navigating away from a route, wherein the user may opt to cancel the transition, but when I dispatch my redux `push` action I will have no idea if it actually succeeded or not.

Example of what I'd like to do (not possible currently):
```js
handleDoSomething: () => {
  if (actions.push({ pathname: '/home' })) {
    // Only do the thing if the transition was successful
    actions.doSomethingAfterTransitioning();
  }
}
```

I know I can do this in the `onEnter` or `componentWillMount` of (in this example the `/home`) route component, but the thing is I only want to `doSomething` in very specific instances (aka when a specific button is pressed). So, in order to leverage these lifecycle methods to conditionally `doSomething` I'd have to set some throwaway state or use a throwaway router query param or something, which is not ideal.

If it's an issue of async routes or whatever (I don't use them personally), then returning a `Promise` would be sufficient.

Any thoughts? Is this a limitation in the `history` API?

CC: @jlongster @mjackson

**Comment by timdorr** [comment]
Are you using React Router? It sounds like you are. There is a `setRouteLeaveHook` there that will do this for you. 

If you want some sort of return from the history methods, this isn't the right repo to suggest this. I would post over on `history`.
