### ISSUE TITLE
Equivalent check will always fail when use a custom `selectLocationState ` (when using Immutable)

### ISSUE THREAD

**Issue by gogoout** [reactjs/react-router-redux#370]
here is the code came from `sync.js`
```JS
// If the store is replayed, update the URL in the browser to match.
  if (adjustUrlOnReplay) {
    var handleStoreChange = function handleStoreChange() {
      var locationInStore = getLocationInStore(true);
      if (currentLocation === locationInStore) {
        return;
      }

      // Update address bar to reflect store state
      isTimeTraveling = true;
      currentLocation = locationInStore;
      history.transitionTo(_extends({}, locationInStore, {
        action: 'PUSH'
      }));
      isTimeTraveling = false;
    };

    unsubscribeFromStore = store.subscribe(handleStoreChange);
    handleStoreChange();
  }
```

the problem is that it using `currentLocation === locationInStore` to check equivalent so when using a `selectLocationState ` like this `state => state.get('route').toJS()` it will always fail.

And this result in many times wasted rendering of Router as each time the store update, the Router renders.

I'm currently using `reselect` to get a  workaround.

**Comment by timdorr** [comment]
You should use a more complex selector. Reselect is a valid option for doing this. You may also wish to make use of Immutable's ability to do equality checks to do your own memoization:
```js
let lastRoute = null
let lastRouteJS = null
const selectLocationState = state => {
  if (state.get('route') !== lastRoute) {
    lastRoute = state.get('route')
    lastRouteJS = lastRoute.toJS()
    return lastRouteJS
  } else {
    return lastRouteJS
  }
}
```

**Comment by gogoout** [comment]
thx for the quick response. Can we add this to the doc?
