### ISSUE TITLE
Basic example fails to build

### ISSUE THREAD

**Issue by timarney** [reactjs/react-router-redux#372]
I'm getting an error when trying to build the basic example code:
Module build failed: ReferenceError: Unknown plugin "transform-es3-member-expression-literals"

**Comment by timdorr** [comment]
Re-run npm install.

**Comment by zorji** [comment]
I am still having this issue

**Comment by namlook** [comment]
same issue here

**Comment by timarney** [comment]
FYI - re-running npm install didn't work for me.

**Comment by namlook** [comment]
however removing the last code block in the `webpack.conf.js` and rerunning `npm install` did worked.

**Comment by zorji** [comment]
I got it working now. namlook is correct you can remove the block there or do an npm install in the parent react-router-redux folder. Because the default config redirect the current react-router-redux to the parent folder, it doesn't have the node_modules required

**Comment by rabeesh** [comment]
Getting same issue.

**Comment by naishe** [comment]
running `npm install` in the parent worked for me.

**Comment by tjwebb** [comment]
> FYI - re-running npm install didn't work for me.

me either
