### ISSUE TITLE
ownProps - not populating ownProps.location

### ISSUE THREAD

**Issue by timarney** [reactjs/react-router-redux#373]
Looking at the docs 

```
function mapStateToProps(state, ownProps) {
  return {
    id: ownProps.params.id,
    filter: ownProps.location.query.filter
  };
}
```
Outside of using Redux connect
```
export default connect(mapStateToProps, null)(MyComponent)
```

If there anything else I need to do to get ownProps to populate with the Router information?

When I log out the values I see it as part of the state object  i.e. 'routing' but it's not showing up in the ownProps object.

**Comment by timdorr** [comment]
You have to be connecting a route component.

**Comment by timarney** [comment]
Thanks works great.  I posted a demo here https://github.com/timarney/react-router-redux-query-params.

**Comment by peterjcaulfield** [comment]
I just got bit by this. Any chance this could be made clearer in the documentation?
