### ISSUE TITLE
syncHistoryWithStore clearing localStorage

### ISSUE THREAD

**Issue by alex-wilmer** [reactjs/react-router-redux#374]
I'm trying to implement redux-storage and am noticing that right after `syncHistoryWithStore` is called my localStorage is kinda wiped:

    console.log('before syncHistoryWithStore', JSON.parse(localStorage.phrase).phrase.past.length)
    // some number like 6 or 10..
    const HISTORY = syncHistoryWithStore(browserHistory, STORE)
    console.log('after syncHistoryWithStore', JSON.parse(localStorage.phrase).phrase.past.length)
    // always 0

**Comment by timdorr** [comment]
Check your reducers. Are you replacing your own reducer with this library's, or are you integrating it via something like combineReducers? That's probably where the error is.

**Comment by alex-wilmer** [comment]
Thank you for the response. After some testing I feel like I've come back to the same bottleneck

This setup works perfectly.. after page load my saved actions restore my previous state:

```
import thunk from 'redux-thunk'
import { Provider as StoreProvider } from 'react-redux'
import { createStore, compose, applyMiddleware } from 'redux'
import { Router, Route, browserHistory } from 'react-router'
import { syncHistoryWithStore } from 'react-router-redux'
import * as storage from 'redux-storage'
import createEngine from 'redux-storage-engine-localstorage'
import finalReducer from './reducers/reduce.js'

const localStorageEngine = createEngine(`phrase`)
const localStorageMiddleware = storage.createMiddleware(localStorageEngine)

const finalCreateStore = compose(
  applyMiddleware(thunk, localStorageMiddleware),
  window.devToolsExtension ? window.devToolsExtension() : f => f
)(createStore)

const STORE = finalCreateStore(storage.reducer(finalReducer))
const load = storage.createLoader(localStorageEngine)
load(STORE)

import App from 'components/App.js'

window.onload = () => {
  ReactDOM.render(
    <StoreProvider store={STORE}>
      <Router history={browserHistory}>
        <Route path="/" component={App} />
      </Router>
    </StoreProvider>,
    document.getElementById('root')
  )
}
```

With the simple addition of `syncHistoryWithStore` the localstorage contents clear up giving nothing to the load function

```
const HISTORY = syncHistoryWithStore(browserHistory, STORE)
...
<Router history={HISTORY}>
```
