### ISSUE TITLE
Error Handling: Warn when locationState.locationBeforeTransitions is undefined

### ISSUE THREAD

**Issue by frantic1048** [reactjs/react-router-redux#378]
Recently I'm using **react-router-redux** with **Immutable**. And I'm using a fully immutable store.

I followed instructions in [README](https://github.com/reactjs/react-router-redux#what-if-i-use-immutablejs-with-my-redux-store) , and used `syncHistoryWithStore` like this:

```js
const history = syncHistoryWithStore(hashHistory, store, {
  selectLocationState: (state) => state.get('routing'),
});
```

Unfortunately, I found the URL never change, but the routing state in store works.

I know if I passed a bad `selectLocationState` which can't get routing state, react-router-redux will surely throw an error with detailed explanation tell me about this.

In this case `state.get('routing')` returns a Immutable object, then `.locationBeforeTransitions` couldn't get correct state.

I digged into to [`react-router-redux/src/sync.js:42`](https://github.com/reactjs/react-router-redux/blob/04036bddd2566f05a1243a4bc2eb2294fb71ce29/src/sync.js#L42) and found the `locationState.locationBeforeTransitions` was replaced by an `initialLocation`. With the logics in other functions, it finally causes a never-changing URL.

Confused for hours then I just simply add `.toJS()` and everything works well.

```js
const history = syncHistoryWithStore(hashHistory, store, {
  selectLocationState: (state) => state.get('routing').toJS(),
});
```

So, I'd recommend to check if `locationState.locationBeforeTransitions` is undefined to determine a provided `selectLocationState` is valid, then throw the error.

How do you think about it ?

**Comment by timdorr** [comment]
Sorry for letting this sit. I think the behavior is fine as it currently exists. Your `selectLocationState` function had an error in it (returning an invalid location descriptor), so the behavior is expected. If anything, we can add some further checks for incorrect returns from that function, but that might be edge case behavior anyways.
