### ISSUE TITLE
problems using react-router-redux with immutable

### ISSUE THREAD

**Issue by dpereira411** [reactjs/react-router-redux#381]
Hello, im trying to use this with immutable but, after two days, I can't seem to configure the `syncHistoryWithStore` properly. I've followed redux-immutable README instructions but its not working.

The demo project is here https://github.com/dpereira411/react-router-redux-immutable

**Comment by ksmithut** [comment]
I'm having trouble with syncHistoryWithStore, as well, but I'm not using immutablejs. When I use the history provided by syncHistoryWithStore, it doesn't work, but if I take it out it works. The redux actions don't seem to be firing.

**Comment by timdorr** [comment]
@dpereira411 There are other issues open about immutable problems. I'm not a user, so I don't have a ton of expertise to fix these quickly. Please only use this issue tracker for identifiable bugs, not support issues.
