### ISSUE TITLE
Fix IE8 Compatibility

### ISSUE THREAD

**Issue by timdorr** [reactjs/react-router-redux#382]
Ref #379

Right now, as bundled via Babel 6, our named exports (`export foo from './foo'`) generate code that breaks in OldIE (at least IE8). There is a pending bug open with Babel to fix this: https://phabricator.babeljs.io/T7322

**Comment by SimenB** [comment]
It's been 4 weeks without a response, maybe just submit the patch? PRs seems to get feedback quicker 😄

**Comment by dyf2015** [comment]
is it fixed?

**Comment by mochachai** [comment]
> is it fixed?

No. But I also hope that will be fixed.

**Comment by andyhu** [comment]
Why is this issue closed?
