### ISSUE TITLE
Accessing current location state from the store

### ISSUE THREAD

**Issue by Mosho1** [reactjs/react-router-redux#384]
The documentation specifically says this shouldn't be done, but I was thinking about a wrapper for the root route that would dispatch the location state given to it in props by react router. Something like this:

```
const wrapRootComponent = (Component) => class WrappedComponent extends React.Component {
    onLocationChange() {
        this.dispatch('ROUTER_LOCATION_CHANGE_FINISHED', this.props.location);
    }

    componentDidMount() {
        this.onLocationChange();
    }

    componentDidUpdate() {
        this.onLocationChange();
    }

    render() {
        return <Component {...this.props}/>
    }
}
```

Which will be used to wrap the user's root component or in a provided `RootRoute` class. Should there be any problems with this? And is this something that will fit in the library?

**Comment by timdorr** [comment]
Your component may update for other reasons than just the location changing. This may cause spurious dispatches. But the general idea is sound. If you listen to this.context.router, you can achieve a more exacting result. That listen is different from history's and should be after transitions, I believe.
