### ISSUE TITLE
Does not work with history@^3

### ISSUE THREAD

**Issue by gajus** [reactjs/react-router-redux#385]
Using:

* react-router-redux@v4.0.4
* history@3.0.0-2

Original issue description (relevant):

> I have spent a good 3 hours trying to understand the underlying issue, but have not found anything that would strike as incompatible. All docs include a variation of this setup that is supposed to work:
> 
> ```js
> import React from 'react';
> import ReactDOM from 'react-dom';
> import {
>     Provider
> } from 'react-redux';
> import store from './store';
> import {
>     Route,
>     Router,
>     useRouterHistory
> } from 'react-router';
> import {
>     createHistory
> } from 'history';
> import {
>     syncHistoryWithStore
> } from 'react-router-redux';
> 
> const browserHistory = useRouterHistory(createHistory)();
> 
> const history = syncHistoryWithStore(browserHistory, store, {
>     selectLocationState (state) {
>         return state.getIn(['route']).toJS();
>     }
> });
> 
> history.listen((location) => {
>     console.log('location', location);
> });
> 
> ReactDOM.render(<Provider store={store}>
>     <Router history={history}>
>         <Route path='*' component={() => { console.log('Hello!'); }}>
>             <div>Hello!</div>
>         </Route>
>     </Router>
> </Provider>, document.querySelector('#app'));
> 
> ```
> 
> However, using `browserHistory` exported from `react-router` works without an issue:
> 
> ```js
> import React from 'react';
> import ReactDOM from 'react-dom';
> import {
>     Provider
> } from 'react-redux';
> import store from './store';
> import {
>     Route,
>     Router,
>     // useRouterHistory
>     browserHistory
> } from 'react-router';
> import {
>     createHistory
> } from 'history';
> import {
>     syncHistoryWithStore
> } from 'react-router-redux';
> 
> // const browserHistory = useRouterHistory(createHistory)();
> 
> const history = syncHistoryWithStore(browserHistory, store, {
>     selectLocationState (state) {
>         return state.getIn(['route']).toJS();
>     }
> });
> 
> history.listen((location) => {
>     console.log('location', location);
> });
> 
> ReactDOM.render(<Provider store={store}>
>     <Router history={history}>
>         <Route path='*' component={() => { console.log('Hello!'); }}>
>             <div>Hello!</div>
>         </Route>
>     </Router>
> </Provider>, document.querySelector('#app'));
> 
> ```
> 
> When I say "does not work", I mean:
> 
> * `history.listen` logs `location` as `undefined`.
> * No routes are resolved.
> 
> When I say "works", I mean:
> 
> * `history.listen` logs `location` as: `{pathname: "/", search: "", hash: "", state: null, action: "POP"…}`
> * `*` route is resolved.>

**Comment by gajus** [comment]
It appears that the reason is:

> Breakage: history.listen no longer calls the callback synchronously once. Use history.getCurrentLocation instead

– https://github.com/mjackson/history/blob/v3.0.0-2/CHANGES.md#300-0

**Comment by timdorr** [comment]
`history` 3.0.0 isn't currently published. We'll revisit once it's out, but there's still a lot of pending changes coming to the API.

**Comment by elliottsj** [comment]
[history@3.0.0 is now published](https://github.com/ReactJSTraining/history/blob/6a92da86cdd1e3311a1fb1e8f9598a1f718820db/CHANGES.md#v300)

**Comment by timdorr** [comment]
react-router doesn't support it yet. So, realistically, we should wait for router to add support and then add it to this library. At the moment, it's essentially impossible to test until that is done.

**Comment by gajus** [comment]
For reference, History v3 has been added to [`react-router#v3.0.0-alpha.2`](https://github.com/reactjs/react-router/blob/v3.0.0-alpha.2/CHANGES.md#v300-alpha2)

**Comment by subicura** [comment]
+1
