### ISSUE TITLE
issue with push() after webpack minification

### ISSUE THREAD

**Issue by lvela** [reactjs/react-router-redux#386]
We are developing an app with a logout button that logs a user out and takes them back to a login page. This is the function we are using:
```
export function logoutCurrentUser() {
  return dispatch => {
    setTimeout(() => {
      dispatch(resetState())
      dispatch(push(LOGIN_URL))
    }, 0)
  }
}
```

This works fine in development, but after the js is minified with webpack the login page is not rendered. The user is logged out but a blank screen is shown. Has anyone encountered issues with push() after minification? Any help would be greatly appreciated.

**Comment by timdorr** [comment]
What kind of mangling are you doing? What is your minifier?

**Comment by lvela** [comment]
We're using `webpack -p`.

**Comment by timdorr** [comment]
Do you have any specific UglifyJS options you're using?

**Comment by antondomratchev** [comment]
@timdorr We are using the HtmlwebpackPlugin and jquery with the ProvidePlugin for webpack. Otherwise just default minification settings.

**Comment by timdorr** [comment]
Is the URL changing when you log out? It sounds like something is getting mangled that shouldn't be.

**Comment by tanepiper** [comment]
Small suggestion but try add:

    /*global LOGIN_URL:true*/

At the top of the file. I assume you are using the define plugin? It creates a global that you need to notify the minifier of. If you can post this Webpack config it might help debug the issue.

**Comment by timdorr** [comment]
Ultimately, this is a tooling problem, not something with this library.

**Comment by ns6482** [comment]
@lvela did you fix  this problem in the end...I'm encountering a similar issue

**Comment by lvela** [comment]
We found a work around but I can't remember the details. Maybe @antondomratchev remembers?

**Comment by antondomratchev** [comment]
@ns6482 Our solution was to use push in browserHistory from react-router instead of react-router-redux. My guess is something wasnt being minified properly.
`import { browserHistory } from 'react-router'`
`browserHistory.push(LOGIN_URL)`
