### ISSUE TITLE
Question: how can I get the routeParams from inside the reducer?

### ISSUE THREAD

**Issue by fixpunkt** [reactjs/react-router-redux#388]
I have a parametrized route. Depending on the parameter, I want to kick off an XHR that will fetch some document from the API.

As far as I understand, I'd have to listen for the LOCATION_CHANGE event inside some reducer and kick off another async action to fetch my document. However, the state does not include the `routeParams`, which means that I'd have to duplicate the route parsing code. How can I avoid this?

Or am I getting redux completely wrong here?

**Comment by timdorr** [comment]
https://github.com/reactjs/react-router-redux#how-do-i-access-router-state-in-a-container-component
