### ISSUE TITLE
How to access params in middleware?

### ISSUE THREAD

**Issue by alex-wilmer** [reactjs/react-router-redux#391]
I'm sure I'm just doing something wrong, but it seems like the information I want is in `ownProps` not in state. I have some middleware that I want to check what the current url params are (using `store.getState()`), but the `routing` reducer from this library seems to only contain `locationBeforeTransitions` key with some info but not params.

**Comment by timdorr** [comment]
The router params are not put in your store. You can get them from your route components.

**Comment by alex-wilmer** [comment]
Hmm okay thanks. Limitation / specific design choice?

**Comment by timdorr** [comment]
Limitation, mainly. The router state isn't serializable, so it can't be put into a store like Redux. Also, we don't have access to it because it lives within the React render loop and Redux exists outside that loop.
