### ISSUE TITLE
Naming conventions `locationBeforeTransitions`

### ISSUE THREAD

**Issue by khankuan** [reactjs/react-router-redux#392]
Hey, thanks for the awesome lib :)

Wanted to question if there is a need to be that explicit in the naming conventions of using `locationBeforeTransitions` instead of `location`. I understand that the state literally means what it says but since the store does not store anything like `location`, would it be more practical to name it shorter?

Cheers :)

**Comment by timdorr** [comment]
You should not be reading that value directly. As the name indicates, it may be out of sync with any async actions the router performs when you transition to another location.

**Comment by khankuan** [comment]
Hmm, would there be a chance where you would want to use it in places like redux-saga? An example such as updating the query params and thus you'll need the existing location?
