### ISSUE TITLE
Opinionated way in redux architecture

### ISSUE THREAD

**Issue by khankuan** [reactjs/react-router-redux#394]
Hi, would like to move the [discussion](https://github.com/reactjs/react-router-redux/issues/392) here to a different issue. It seems like the state in store is recommended not to be used at all. This would assume that libraries such as `redux-thunk` or `redux-saga` has no easy way of accessing the url params. Was hoping that the library would aim to have url to be controlled by redux, besides just making time travel work. Thoughts? Cheers :)

**Comment by timdorr** [comment]
There is a bold section of the README about this:

> This library is not necessary for using Redux together with React Router. You can use the two together just fine without any additional libraries. It is useful if you care about recording, persisting, and replaying user actions, using time travel. If you don't care about these features, just [use Redux and React Router directly](http://stackoverflow.com/questions/36722584/how-to-sync-redux-state-and-url-hash-tag-params/36749963#36749963).

Don't use this library to connect Redux middleware and reducers to the Router. There are numerous problems with trying to use that (mostly centered around it being impossible to serialize the router's state) and not the intended purposes of this library. It's sole purpose is to keep track of locations for developer-only features like time travel.

**Comment by khankuan** [comment]
Alright, thanks :)
