### ISSUE TITLE
Is it an expected behavior that `onEnter` triggered both on server and client?

### ISSUE THREAD

**Issue by lovio** [reactjs/react-router-redux#395]
Hi, guys. There are some data-fetching logics in `onEnter` in my SSR case. But `onEnter` is triggered both on server and client. Data will be fetched twice. Is it an expected behavior for `react-router-redux`?

**Comment by timdorr** [comment]
That is not an issue with this library, it's something with React Router.

But yes, onEnter hooks are expected to be triggered in all environments. It's core to the routing engine.
