### ISSUE TITLE
Why does action.payload not contain params.

### ISSUE THREAD

**Issue by mattjdev** [reactjs/react-router-redux#396]
If I have a route with some parameters like `/some/path/:myParam`, I would like to be able to use that info in my reducer, but the action would look like this: 
```
{
  type: "@@router/LOCATION_CHANGE",
  payload: {
    $searchBase: Object
    action: "PUSH"
    hash: ""
    key: "inrmfk"
    pathname: "/some/path/lkjhgfdsa"
    query: Object     // <--- this contains query params which is great! 
    search: ""
    state: null
  }
}
```
I would have to parse the pathname 'manually' instead of just accessing something like `action.payload.params.myParam`

**Comment by timdorr** [comment]
https://github.com/reactjs/react-router-redux#how-do-i-access-router-state-in-a-container-component

**Comment by mattjdev** [comment]
The problem is I'd rather not have to wire up a container to dispatch the event when you already dispatch a `LOCATION_CHANGED` event the I can use in my reducer. I would just rather the action payload have more information like those props have, but all I _really_ need (and expect) is for the route parameters to be parsed out into an object or something.

**Comment by timdorr** [comment]
We don't hook into router, just into the `history` instance. That doesn't have access to router params. You can only get them from your route components.
