### ISSUE TITLE
Link onClick handlers supported in 3.0.0?

### ISSUE THREAD

**Issue by mrdanimal** [reactjs/react-router-redux#397]
I'm using 3.0.0, and `onClick` handlers on `Link` components don't seem to work at all. Is this expected behavior?

**Comment by timdorr** [comment]
Nope, definitely not. I haven't heard of anything like this. Can you share an example?

**Comment by mrdanimal** [comment]
Actually, when I tried to isolate a dead simple example, it worked fine. So it's got to be something I'm misunderstanding about my own application in the few cases I was trying. As long as I know it _should_ work, then I can sort out what I'm doing wrong in these other cases. No need for you to debug it. Thanks!
