### ISSUE TITLE
history package breaks first sync. call to `listener` on next major

### ISSUE THREAD

**Issue by yoadsn** [reactjs/react-router-redux#404]
Hey,
I have noticed that the history package used by react-router will break the behavior of the first synchronous call to listener. See [here](https://github.com/ReactJSTraining/history/blob/master/CHANGES.md#300-0).

react-router-redux (and maybe also react-router itself) rely on this behavior - [See relevant code here](https://github.com/reactjs/react-router-redux/blob/master/src/sync.js#L119-L122).

I wonder, when react-router would depend on the next version, will this library would break? (This library *would* perform a first call to the listener, while this call would not be expected from the usual history behavior).

Any thoughts?

**Comment by timdorr** [comment]
Yes, but we're still a bit of a ways off from adding history 3.0 support to Router. We'll update this library where appropriate when that lands.
