### ISSUE TITLE
Is there a way to get route name outside of the route-component

### ISSUE THREAD

**Issue by leecade** [reactjs/react-router-redux#407]
`pathname` injected through `routing`, but no route name, confusing

**Comment by timdorr** [comment]
https://github.com/reactjs/react-router-redux#how-do-i-access-router-state-in-a-container-component

**Comment by leecade** [comment]
@timdorr I noticed the doc, react-router injected some info to route-component, but I need to access the state outside of the route-component

Maybe react-router-redux provide a more graceful way to get current route name and query, `props. routing` is a possible way, but only `pathname` in it

**Comment by timdorr** [comment]
No, this is not possible. We've talked about this a lot, so see previous issues in this repo.
