### ISSUE TITLE
Request for custom Link

### ISSUE THREAD

**Issue by fingermark** [reactjs/react-router-redux#409]
This will likely get shot down, but I just wanted to bring it up in case I was doing something wrong.

I needed to use activeClassName on my react-router `Link` and found that it would only work intermittently.  I had to pass `{pure: false}` to redux's `connect` for it to work 100% of them.  Once I did that my component with the `<Link />` was rendering whenever any state changed.  After talking with someone on IRC they mentioned that it's because shouldComponentUpdate and context aren't mixing well.

The only solution I could come up with was to create my own custom Link component that reads the router state.

Would it be possible for react router to implement this component for us in the future?

**Comment by timdorr** [comment]
Wrong repo. But this is coming: reactjs/react-router#3430 You can get it now with `npm install react-router@next`
