### ISSUE TITLE
Possible regression in 4.0.5

### ISSUE THREAD

**Issue by khankuan** [reactjs/react-router-redux#410]
Hi, after updating from `4.0.4`, i observed 2 bugs:
1) Nothing happens upon linking any link the first time.
2) Firing an action the first time triggers `LOCATION_CHANGE`.

Both bugs went away after downgrading to `4.0.4`.

**Comment by dlmr** [comment]
1. What do you mean with _"linking any link"_? You mean nothing happens the first time you click on a link?
2. Are you talking about firing one of these actions? https://github.com/reactjs/react-router-redux#pushlocation-replacelocation-gonumber-goback-goforward 

The change that was done in `4.0.5` was minimal and should not affect anything other than when using server side rendering on the initial load. Do you have an example repo that shows this behaviour?

**Comment by khankuan** [comment]
1. My bad, i meant clicking any link.
2. Nope, these are app specific actions.

Unfortunately the repo is a private one. I'm doing SSR. Could it be the same changes are also applied on client side and caused the bug?

**Comment by timdorr** [comment]
Can you share some of the code you have for setting up your SSR and the client side syncing setup?

**Comment by khankuan** [comment]
Hopefully its useful:
```

// client
let history = useScroll(() => browserHistory)();
const store = createStore(history, { initialData: window.__data });
const routes = appRoutes(store);
history = syncHistoryWithStore(history, store)
history.listenBefore((location, callback) => {
  match({ location, routes }, (err, redirectLocation, renderProps) => (
    someApi.then(callback)
  ));
});

// server
const memoryHistory = createHistory(req.originalUrl);
const store = createStore(memoryHistory);
const history = syncHistoryWithStore(memoryHistory, store);
```

**Comment by khankuan** [comment]
It seems like `history.state` has a `key` that is different from `store.routing.locationsBeforeTransition`. Syncstore thinks that they are different and decides to fire an action for `LOCATION_CHANGE`. I could stop that by deleting `store.routing` on server side `__data`.

**Comment by dlmr** [comment]
Could you show the state that you have from the server and what the URL is in the browser along with the history state?

Which library is `useScroll`? Not sure if that has anything to do with this but it is something different from the example setup.

**Comment by khankuan** [comment]
`useScroll` comes from https://github.com/taion/scroll-behavior

![screen shot 2016-06-11 at 10 09 10 am](https://cloud.githubusercontent.com/assets/1406170/15986434/b09a2e8a-2fbc-11e6-8222-b737eda99c90.png)

This is the one reverting to `4.0.4`:
![screen shot 2016-06-11 at 10 11 04 am](https://cloud.githubusercontent.com/assets/1406170/15986441/e3cfaaf0-2fbc-11e6-8502-3e4650c485f8.png)

**Comment by dlmr** [comment]
I can't replicate this in the server example that is in this repo. The `history.state.key` is not the same as the key in the store as you mention but it seems like that does not matter since it works fine for me.

Could you see if you could make some small modifications to the example so that it shows the same behaviour as you are seeing?

One thing I notice however is that it seems like you are using an old version of `scroll-behavior` and updating it or switching to https://github.com/taion/react-router-scroll might help.
