### ISSUE TITLE
What was the problem with links in react-router that affected react-router-redux

### ISSUE THREAD

**Issue by jamestwiggle** [reactjs/react-router-redux#411]
I vaguely remember a couple comments on a github issue that discussed some problems between links working with redux. I don't exactly remember the problem but I recently ran into an issue where I have a link in my redux application (using react-router-redux) and when I click the link it updates the location to `/listings/boats` the `boats` portion is an optional parameter. At that point theres a container component that checks the url has a parameter, if it does it fetches that parameter from the database. If I open a new tab with the same `url` the `<Link>` points to it will check the parameter and fetch the boat listings. However if I click the link that will send me to the url it still checks the link to see if it has a parameter and to make sure it was running the check I added some logging statements on the client, and logging statements on the server to see if there was anything going wrong. When clicking from the `<Link>`however doesn't fetch/hit the database for the `boat` listings. I'm wondering if this is the issue with the links working with redux. If it is has there been any solution found for this? If it's not do you have any idea why this may be occurring?

**Comment by timdorr** [comment]
You need to implement `componentWillReceiveProps`. This isn't a react-router-redux issue, it's with React Router. And it's not even an issue, it's just something you need to implement.

**Comment by jamestwiggle** [comment]
If it has to do with react-router is there a documentation section on something like this, I've been looking through docs and can't find it. If theres not thanks for the information.
