### ISSUE TITLE
Persist full history

### ISSUE THREAD

**Issue by alecperkey** [reactjs/react-router-redux#413]
Hello,

Is there a best practice to store the full history of a users' session? I would like to also hook into when the user leaves the site (if possible) to first post the recent visited URLs to my server. Alternatively, I could use an analytics platform with a widget for recently viewed router contexts/urls. 

My problem is explained in further detail here, and I think it would be a common enough use case for adding to the readme/examples directory/faq/etc...

ref: http://stackoverflow.com/questions/38012790/store-browserhistory-using-history-js-in-react-redux-architecture-with-ssr

Looking forward,
Alec

**Comment by timdorr** [comment]
You should subscribe to `history.listen` separately if you want to keep a full log of history for the session. This library is for dealing with time travel in Redux.
