### ISSUE TITLE
Routing with basename results on double basename in url

### ISSUE THREAD

**Issue by X-Tender** [reactjs/react-router-redux#414]
I try to add the basename property to the react-router-redux. Here are some snippets of my implementation:

store.js
```
const browserHistory = useRouterHistory(useBasename(createHistory))({
	basename: '/myPage/public'
});

const enhancers = compose(
	applyMiddleware(routerMiddleware(browserHistory)),
	window.devToolsExtension ? window.devToolsExtension() : f => f
);

const store = createStore( rootReducer, defaultState, enhancers );
export const history = syncHistoryWithStore( browserHistory, store );
export default store;
```

index.js
```
const router = (
	<Provider store={ store }>
		<Router history={ history }  >
			<Route path="/" component={ App }>
				<IndexRoute component={ ClientLogin }/>
				<Route path="admin" component={ AdminLogin }/>
				<Route path=":language/:issueName(/:page)" component={ Issue }/>
				<Route path=":language/:issueName(/:gender)(/:chapter/:page)" component={ Issue }/>
				<Route path="*" component={ NoMatch }/>
			</Route>
		</Router>
	</Provider>
);
```

history is from the store.js

The routing itself works. when I go to the URL:
`http://localhost/myPage/public/admin`
I see the admin pannel, also the other, more komplex routes work.
But when I try to navigate via the push action:

```
store.dispatch(push( "/admin"));
```
I end up at this URL:
```
http://localhost/myPage/public/myPage/public/admin
```

Did I missed something?
my html head have no base tag or something like that (I think thats correct)

**Comment by X-Tender** [comment]
OK I played a bit arround and it seams that this part:
```
const browserHistory = useRouterHistory(useBasename(createHistory))({
    basename: '/myPage/public'
});
```
is not correct. 
Either I use `useRouterHistory` or `useBasename` not both. But which is more correct?!

**Comment by timdorr** [comment]
[`useRouterHistory` already applies `useBasename`](https://github.com/reactjs/react-router/blob/master/modules/useRouterHistory.js). You should just keep with `useRouterHistory` only. You can pass options into it.
