### ISSUE TITLE
Clarify usage with Immutable.js

### ISSUE THREAD

**Issue by sfentress** [reactjs/react-router-redux#415]
In the readme, it says

> Provide your own reducer function that will receive actions of type LOCATION_CHANGE and return the payload merged into state.

This isn't enough information, and the user needs to look through the source code to understand where to actually put the data.

Can we change this to something like

1. Provide your own reducer function that will receive actions of type LOCATION_CHANGE and return the payload merged into the `locationBeforeTransitions` property of the routing state. e.g. `state.set("routing", {locationBeforeTransitions: action.payload})`.

**Comment by timdorr** [comment]
I'd be happy to accept a PR for this change. We can discuss specific changes that way.
