### ISSUE TITLE
currentLocation not the same as document.location

### ISSUE THREAD

**Issue by Kosmin** [reactjs/react-router-redux#419]
## Problem
This issue appears when using a hybrid application which uses both push-state and server-side routing, in a Rails environment using Turbolinks. Here's the use case:

1.  navigate to a page using pushstate navigation with the React Router, call it `page 1`

2.  navigate to a page rendered on the server side which isn't using the react router, call it `page 2`
     - at this point, a `@@router/LOCATION_CHANGE` should be fired when leaving `page 1`
     - turbolinks will then load `page 2`, and `getLocationInStore` will return `page 2`

3. navigate to a new page which uses the react router and pushstate navigation, say `page 3`.
     -  here's where the problem happens: `store.getState().routing.locationBeforeTransitions` returns `page 2` instead of `page 3`, since the `react-router-redux` didn't fire an event for the transition between page 2 and page 3.

## Solution
To get around this, I used a `react-router-redux` action to manually force the route to be correct, whenever it isn't initialized properly:
```
  function fixStoreRoute() {
    var storeLocation = store.getState().routing.locationBeforeTransitions;

    if(document.location.pathname != storeLocation.pathname) {
      store.dispatch(replace(document.location.href));

      // Must first wait for the document to be ready, after pushstate navigation is fired
      setTimeout(() => {
        Turbolinks.visit(document.location.href);
      }, 1);
    }
  }

  $(document).on('page:load', (event) => {
    fixStoreRoute();
  });
```

In my humble opinion, the store should never be allowed to have a different path in the store than in the `document.location`. Am I doing something wrong ? Shouldn't this be supported by `react-router-redux`, or maybe there's a better way of doing this ?

**Comment by timdorr** [comment]
This isn't something that's going to be supported. You're navigating outside of `history`'s control. `history`'s location is not the same as the browser location (it has extra properties like `key`). You shouldn't be trying to use turbolinks and react-router in the same app. They're not going to behave well at all.

**Comment by Kosmin** [comment]
Alright, thanks for the reply @timdorr, that makes sense.
