### ISSUE TITLE
Using Immutable.js makes app re-render on each store change

### ISSUE THREAD

**Issue by skozin** [reactjs/react-router-redux#421]
When using react-router-redux with Immutable.js, the app re-renders each time anything in store changes.

The reason is that converting from Immutable.js Map to plain JS object makes new object each time `selectLocationState` function is called; this makes the [`currentLocation === lastPublishedLocation` checks in sync.js](https://github.com/reactjs/react-router-redux/blob/9483ea4/src/sync.js#L112) fail, which, in turn, causes new router transition to happen and eventually re-render everything. The stack looks like this:

* ReactComponent.setState (react: ReactComponent.js)
* [(anonymous function) (react-router: Router.js:88)](https://github.com/reactjs/react-router/blob/112cce4/modules/Router.js#L88)
* ...
* [(anonymous function) (react-router: createTransitionManager.js:273)](https://github.com/reactjs/react-router/blob/112cce4/modules/createTransitionManager.js#L273)
* [(anonymous function) (react-router-redux: sync.js:117)](https://github.com/reactjs/react-router-redux/blob/9483ea4/src/sync.js#L117)
* dispatch (redux: createStore.js)

This hurts performance; also, it causes errors in my app because such re-rendering sometimes makes `mapStateToProps` functions of nested components execute before the ones of their parents, as react-router-redux gets all Redux state changes before any component wrapped with `connect`.

The temporary workaround for me was to memoize the `selectLocationState` function like this:

```js
let lastLocationState = null
let lastLocationStatePlain = null

export function selectLocationState(state) {
  let locationState = state.get('routing')
  if (locationState != lastLocationState) {
    lastLocationState = locationState
    lastLocationStatePlain = locationState.toJS()
  }
  return lastLocationStatePlain
}
```

But this is only a workaround. I think that the proper fix would be to use deep equality in `sync.js` instead of strict equality.

What do you think? I will be happy to make a PR with the fix.

**Comment by timdorr** [comment]
No, because that would significantly slow things down for what should be a very simple check. 

The location in that part of your state tree should be the same object reference (in addition to the immutable wrapper being the same reference). Something else must be going wrong for this to be failing like this.

**Comment by skozin** [comment]
@timdorr, yeah, this would certainly incur some performance cost. I'm not sure that it will be significant, but anyway.

So you mean that I should not deeply convert the payload I get from `LOCATION_CHANGE` action into Immutable.js object using `Immutable.fromJS`, but instead just place the plain payload inside Immutable.js wrapper? It seems this is the only way to preserve the same object reference without performing memoization of `selectLocationState`.

This would work, but now I cannot use strict equality in my components to check if location has changed. On the other hand, it seems that the main goal of `react-router-redux` is not providing location through redux store, but just allowing react-router work with time traveling debugger, so in this case it's not a problem.
