### ISSUE TITLE
Dispatched push does not show up in dev tool

### ISSUE THREAD

**Issue by felixandersen** [reactjs/react-router-redux#423]
Hello.

I have successfully used `this.context.router.push('/')` by listing router in contextTypes for my component.

But when I try navigate, outside of a component, by dispatching the push action I run into problems. I have noted that others have had problems when forgetting to apply `routerMiddleware` when setting up the store. But I have double checked this. It seems to be set up properly and my symptoms are a different. I dispatch the action like this

```
import { sessionExpired } from '../modules/auth'
import { push } from 'react-router-redux'

logOut = (dispatch) => {
  dispatch(sessionExpired())
  dispatch(push('/login'))
}
```

the action created by `sessionExpired` is visible in my dev tools log of my redux store. The action created by `push` does not even show up. A test of dispatching a `{action: "random_test"}` shows that arbitrary actions do show up in the log.

My store setup, that also adds a couple of development tools along the way, looks like this:

```
import { applyMiddleware, compose, createStore } from 'redux'
import thunk from 'redux-thunk'
import { browserHistory } from 'react-router'
import { routerMiddleware as reactRouterReduxMiddleware } from 'react-router-redux'
import rootReducer from './rootReducer'

export default function configureStore (initialState = {}) {
  // Compose final middleware and use devtools in debug environment
  let middleware = applyMiddleware(reactRouterReduxMiddleware(browserHistory), thunk)
  if (__DEBUG__) {
    const devTools = window.devToolsExtension
      ? window.devToolsExtension()
      : require('containers/DevTools').default.instrument()
    middleware = compose(middleware, devTools)
  }

  // Create final store and subscribe router in debug env ie. for devtools
  const store = middleware(createStore)(rootReducer, initialState)

  if (module.hot) {
    module.hot.accept('./rootReducer', () => {
      const nextRootReducer = require('./rootReducer').default

      store.replaceReducer(nextRootReducer)
    })
  }
  return store
}
```

How can it be that the action created by `push` does not even show up? I have done some `console.log` dumps of the object the `push` function returns, and it looks like it's correctly formatted. Any ideas?

**Comment by timdorr** [comment]
You don't have the reducer added to your store. Simple as that.

**Comment by felixandersen** [comment]
I actually think that I have it added to the store. The imported `rootReducer` comes from the following file

```
import { combineReducers } from 'redux'
import { routerReducer as routing } from 'react-router-redux'
import { reducer as form } from 'redux-form'
import auth from './modules/auth'

export default combineReducers({
  auth,
  routing
})

```

But even if I did not have the reducer added, the action should still show up in the devtool log of actions? Or am I mistaken?

**Comment by felixandersen** [comment]
@timdorr What are your thoughts after my response above? Would you consider opening the issue again? I really like the react-router-redux approach and I would hate to have to find another solution.

**Comment by joeruello** [comment]
@felixandersen A little late, I had the same issue. For anyone else: Make sure you're using `syncHistoryWithStore` correctly.
