### ISSUE TITLE
routeMiddleware doesn't work with thunk middleware from Redux

### ISSUE THREAD

**Issue by LGullaci** [reactjs/react-router-redux#426]
Hi,

I am newer in react router and more in react router redux, and when i used the routeMiddleware with thunk middleware from redux, i can't dispatch any reducer. How can i fixed this problem? 

Thanks.

**Comment by timdorr** [comment]
You don't need this library right now. It sounds like you need to do some more reading on Redux and React Router first. They work just fine without this library. This is only for some developer conveniences, but after you've learned the basics.
