### ISSUE TITLE
Where to save “next pathname” if redirecting to Login in react-router?

### ISSUE THREAD

**Issue by Lucas-Qi** [reactjs/react-router-redux#430]
I use react-router and react-router-redux, I will redirect user to Login page if he tries to visit a page requiring logged in without logging in:
```
<Route path="/react/myprofile" component={MyProfile} onEnter={requireAuth} /></Route>

function requireAuth(nextState, replace) {
   const state_user = store.getState().auth.user;
   if (!state_user) {
     console.log('not logged in, redirect')
     replace({
       pathname: '/react/login',
       state: { nextPathname: nextState.location.pathname }
     })
   }
}
```

And after the user logs in, I will redirect the user to "/react/myprofile": in my redux-saga, I do the following:
```
const route_state = get routing state from the store;
redirectTo(route_state.locationBeforeTransitions.state.nextPathname);
```
As above, I have to retrieve the information from
```route_state.locationBeforeTransitions.state.nextPathname```, it is too verbose, and it seems strange to do as this.

I wonder if there is a better way to do this? Thanks.

**Comment by mjrussell** [comment]
You could use the query parameter of the location description so it would be like `/react/login?redirect=%2freact%2fmyprofile`. And in your login component, check for the presence of the query parameter. This is something that doesn't require react-router-redux at all.

We do a similar thing in redux-auth-wrapper - https://github.com/mjrussell/redux-auth-wrapper/blob/master/examples/basic/components/Login.js

**Comment by timdorr** [comment]
I have these onEnter hooks on my routes: 
```js
const notAuthed = auth => {
  return (nextState, replace) => {
    let { location: { query } } = nextState
    if (auth.loggedIn) replace({ pathname: query && query.return_to || '/' })
  }
}

const requireAuth = auth => {
  return (nextState, replace) => {
    if (!auth.loggedIn) replace({ pathname: '/login', query: { return_to: nextState.location.pathname } })
  }
}
```
Work just fine for me.

**Comment by Lucas-Qi** [comment]
Thanks a lot buddies @timdorr  @mjrussell

**Comment by Lucas-Qi** [comment]
1

**Comment by pkyeck** [comment]
@timdorr where does the `auth` param come from in your example?

**Comment by cbosco** [comment]
@pkyeck this probably comes from his state -- you can use a higher order function for this. Where you attach `onEnter` pass in `store` or some member

**Comment by timdorr** [comment]
Yes, I'm using mobx in this case, but it looks like this:

index.js (entry point)
```js
ReactDOM.render(
  <Provider auth={auth}>
    <Router history={browserHistory} children={routes(auth)} />
  </Provider>,
  document.getElementById('root')
)
```

routes.js
```js
const routes = auth => [
  <Route path="/login" component={Login} onEnter={notAuthed(auth)} />,
  <Route path="/" component={App} onEnter={requireAuth(auth)}>
    <IndexRoute component={Dashboard} />
    <Route path="users" component={Users}>
      <Route path=":user_id" component={UserDetails} />
    </Route>
  </Route>
]

export default routes
```
