### ISSUE TITLE
Uncaught Invariant Violation: You have provided a history object created with history v3.x. This version of React Router is not compatible with v3 history objects. Please use history v2.x instead.

### ISSUE THREAD

**Issue by leetercola** [reactjs/react-router-redux#435]
Using react-router@2.6.1 and I started getting the warning 2 about the wrong history object. I read some of the change logs which mentioned using the singletons included in react-router but we already are. We are using react-router-redux's syncHistoryWithStore to keep our redux store in sync with history changes. I don't believe this is causing an error because it hasn't been updated. I can't find any other reason why using react-routers own hash history would return the error.

import { Router, hashHistory } from 'react-router'
import { syncHistoryWithStore } from 'react-router-redux'

const enhancedHistory = syncHistoryWithStore(hashHistory, store, {
  selectLocationState (state) {
    return state.get('routing').toJS()
  }
})

  <Router history={enhancedHistory}>
        { routes(store) }
  </Router>

**Comment by emmya** [comment]
Did you figure this out? I'm having this is issue now.
