### ISSUE TITLE
How to trigger action when CHNAGE_LOCATION ocurred?

### ISSUE THREAD

**Issue by WenXuanYuan** [reactjs/react-router-redux#437]
I have an action
<pre>
export function resetState (state) {
    return {
        type: RESET_STATE,
        payload: {
            ...state, 
        }
    };
};
</pre>
I want to trigger it when location changed, so I wrote a reducer
<pre>
import { LOCATION_CHANGE } from 'react-router-redux';

const ACTION_HANDLERS = {
    [LOCATION_CHANGE]: (state, action) => {

        // here I want to trigger action resetState, What should I do ?

        return { ...state,
                     pathname: action.payload.pathname,
                     query: action.payload.query
        }
    };

const initialState = {
    pathname: '',
    query: {}
};
export default function locationReducer (state = initialState, action) {
  const handler = ACTION_HANDLERS[action.type]

  return handler ? handler(state, action) : state
}
</pre>

resetState will get parameters from location query, so when location changed resetState will be triggered, How should I do?

**Comment by timdorr** [comment]
You could use a middleware.

**Comment by WenXuanYuan** [comment]
@timdorr Ok, thanks for your guide!
