### ISSUE TITLE
@types/react-router-redux/index.d.ts - 

### ISSUE THREAD

**Issue by MarkPieszak** [reactjs/react-router-redux#438]
(This may not be the best place to post this issue, I apologize in advance, as it's related to the `@types` for react-router-redux)

I'm getting an issue when using the `@types/react-redux-router` with TypeScript 2.0 (inside of the `@types` itself. Has anyone ran into this before by any chance?

> @types/react-router-redux/index.d.ts -  error TS2305: Module '"history"' has no
 exported member 'History'.

**Comment by timdorr** [comment]
Please open this on the appropriate repo. The typescript definitions don't live here.

**Comment by MarkPieszak** [comment]
Opened an issue on here: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/10686

TS2.0 not meshing with the Types defined. Thanks Tim, apologies.

**Comment by MarkPieszak** [comment]
@timdorr It seems that posting issues there seem to go nowhere, is there a better place I should be posting the issue?

**Comment by timdorr** [comment]
I would tag whomever authored them in that issue.
