### ISSUE TITLE
syncHistoryWithStore Circular References

### ISSUE THREAD

**Issue by jhicken** [reactjs/react-router-redux#442]
Is routerMiddleware supposed to work with syncHistoryWithStore? Is seems to me like there is no way to use them together.

Or if there is a way I'm too foolish to see it.

``` javascript
**store** = compose(
  applyMiddleware(apiMiddleware, thunk, routerMiddleware(**history**)),
  typeof window === 'object' && typeof window.devToolsExtension !== 'undefined' ?
    window.devToolsExtension() : f => f
)(createStore)(allAppReducers)

**history** = syncHistoryWithStore(browserHistory, **store**)
```

Perhaps this is explained in the documentation and i just missed it?

It seems like `**history**` should be used by routerMiddleware. Is that not the case?

**Comment by timdorr** [comment]
Heh, yep, that's certainly a bit confusing. However, it's fine to use the original `browserHistory` (or `hashHistory`) with the middleware, as they operate on different parts of the API. The action creators don't overlap with the syncing function, so there's no actual circular reference under the hood.

**Comment by jhicken** [comment]
Cool any chance we could put that in the documentation?

**Comment by timdorr** [comment]
I'm going to be dropping routerMiddleware in the next major, since it's a bad pattern. I don't want to improve documentation around it to discourage its use.

**Comment by garethderioth** [comment]
@timdorr So it is ok to declare the `syncHistoryWithStore` importing `browserHistory` the and by the other side also import the `browserHistory` to apply it into the `routerMiddleware`?

For example:

index.js
```javascript
import React from 'react';
import { render } from 'react-dom';
import { browserHistory } from 'react-router';
import { syncHistoryWithStore } from 'react-router-redux';
import configureStore from './store/configureStore';
import Root from './containers/Root';

const store = configureStore();
const history = syncHistoryWithStore(browserHistory, store);

render(
  <Root store={store} history={history} />,
  document.getElementById('root')
);
```

configureStore.js
```javascript
import { createStore, applyMiddleware } from 'redux';
import thunk from 'redux-thunk';
import rootReducer from '../reducers';
import { browserHistory } from 'react-router';
import { routerMiddleware } from 'react-router-redux';

const middleware = routerMiddleware(browserHistory)

export default function configureStore(preloadedState) {
  return createStore(
    rootReducer,
    preloadedState,
    applyMiddleware(thunk, middleware),
  );
}
```

**Comment by ovaldi** [comment]
Mark!
