### ISSUE TITLE
LOCATION_CHANGE on page load?

### ISSUE THREAD

**Issue by chrisabrams** [reactjs/react-router-redux#447]
Is it possible to get `LOCATION_CHANGE` to fire on page load? I don't see it until a routing event happens, but I would think the initial page load would qualify?

**Comment by chrisabrams** [comment]
Disregard, it looks like this is being resolved: https://github.com/reactjs/react-router-redux/pull/445

**Comment by xtrinch** [comment]
I'm still not seeing it fire on page load.
