### ISSUE TITLE
url replaced but component not loading

### ISSUE THREAD

**Issue by lvtrvd** [reactjs/react-router-redux#449]
I am redirecting the application to notfound url from the action if ajax return 401
`dispatch(routerActions.push(constant.PREFIX+'notfound/'));`
 only url updated to /notfound component not loading itself
I have to refresh to load the notfound component.

any solution ?

**Comment by timdorr** [comment]
You must have a route that exists at that URL.

**Comment by lvtrvd** [comment]
here is my routes.js fiel code




`<Provider store={store}>
    <Router history={history}>
        <Route path="/admin" component={AppBase} onEnter={requireAuth} >

            {/* Default route*/}
            <IndexRoute component={UsersList} />
            <Route path="users" component={UsersList}/>
            <Route path="product" component={ProductsList}/>
        </Route>
        <Route path="/admin" component={BasePage}>
            <Route path="login" component={Login}/>
            <Route path="notfound" component={NotFound}/>
        </Route>
        <Route path="*" component={NotFound}/>
    </Router>
    </Provider>,`


all routes are working fine expect I redirect  it to /notfound from action using

dispatch(routerActions.push(constant.PREFIX+'notfound/'));

**Comment by lvtrvd** [comment]
I have resolved the issues as the problem is with my History Configuration

@timdorr Thanks for your support
