### ISSUE TITLE
In IE 11 and Edge, hash change doesn't fire @@router/LOCATION_CHANGE

### ISSUE THREAD

**Issue by flowersinthesand** [reactjs/react-router-redux#451]
I found that in IE 11 and Edge changing hash part in uri doesn't fire `@@router/LOCATION_CHANGE` unlike other browsers though IE 11 supports [Hashchange event](http://caniuse.com/#feat=hashchange).

To reproduce, run the server example and manipulate hash part in IE. I also set some value to location.hash through the developer console but it didn't work.

IE 11
![screen shot 2016-09-05 at 5 14 41 pm](https://cloud.githubusercontent.com/assets/1095042/18241464/43398660-738c-11e6-8c80-5afaa1361a5f.png)

Edge
![screen shot 2016-09-05 at 5 14 24 pm](https://cloud.githubusercontent.com/assets/1095042/18241465/43424e58-738c-11e6-9ebd-b3ac55ed9d40.png)

Chrome
<img width="1280" alt="screen shot 2016-09-05 at 5 15 28 pm" src="https://cloud.githubusercontent.com/assets/1095042/18241505/79f9b1ca-738c-11e6-9ba5-f6086d50b768.png">

**Comment by timdorr** [comment]
This is likely an upstream bug with history. We don't control this kind of thing in this library.
