### ISSUE TITLE
How to use react-router-redux without using react-router? 

### ISSUE THREAD

**Issue by aug828** [reactjs/react-router-redux#452]
Our app is a single page app, so react-router doesn't make sense to us. We use react-router-redux since it was still redux-simple-router. There are two functions we are using:
1. when user input url in the address bar, a INIT_PATH is fired to notify our app that the location is changed. The app will start from there. 
2. when user navigation caused a location change in the redux store, the redux-simple-router will get notified and update the address bar accordingly. 

Now we want to update the redux-simple-router to the newest version react-router-redux 4.*, but we still don't want to use react-router. Is there anyway to keep react-router completely out of the picture? 

In all examples, I see the enhanced history object injected in react-router, like this 
`<Router history={history}>`.  How do I hook up this enhanced history object with my store without using react-router? 

Also, in the newest version, when user inputs a url in the address bar, there's no LOCATION_CHANGE event fired. How to make this happen?

**Comment by timdorr** [comment]
There is no dependency on react-router with this project. It's a bit of a misnomer. `history-redux` would be a more appropriate name. It simply syncs your history with your store. That's it. 

So, just use the history returned from `syncHistoryWithStore`.

**Comment by aug828** [comment]
Can you be more specific about how to use the enhanced history to fire a LOCATION_CHANGE action?

**Comment by timdorr** [comment]
If you're using that history instance that's been synced with your Redux store, then it will dispatch those actions automatically into the store whenever you do something like `history.push`.

**Comment by aug828** [comment]
I remember in the 1.* versions, we don't have to use history API directly. How was the UPDATE_PATH action fired?

**Comment by timdorr** [comment]
React Router was calling those APIs under the hood. If you're not using Router, then you would call them directly.

**Comment by aug828** [comment]
We never used react-router. So who's calling those API in version 1.*?

**Comment by timdorr** [comment]
You would have been. If you call out to `window.history.pushState`, that will trigger the event listeners in `history`, which the current version will do as well.

**Comment by aug828** [comment]
Okay. I found out what's really confusing me. The problem is: we can't use the enhanced history and routerMiddleware together. It's an egg and chicken issue. 

To use the enhanced history:
`const history = syncHistoryWithStore(createHistory(), store)`

To use routerMiddleware:
`const middleware = routerMiddleware(createHistory())
const store = createStore(
  reducers,
  applyMiddleware(middleware)
)`

So, to use the enhanced history, we need to create store first. To create store, we need to apply the routerMiddleware, which requires the enhanced history. It's a egg and chicken issue. So there's no way we can use routerMiddleware with the enhanced history. We can only use routerMiddleware with simple createHistory().

**Comment by smolyakoff** [comment]
@aug828 Were you able to solve chicken and egg issue?
