### ISSUE TITLE
Issue navigation events via Redux actions server-side

### ISSUE THREAD

**Issue by webdif** [reactjs/react-router-redux#453]
In the README, we have a example for dispatch navigation action:

```js
import { createStore, combineReducers, applyMiddleware } from 'redux';
import { routerMiddleware, push } from 'react-router-redux'

// Apply the middleware to the store
const middleware = routerMiddleware(browserHistory)
const store = createStore(
  reducers,
  applyMiddleware(middleware)
)

// Dispatch from anywhere like normal.
store.dispatch(push('/foo'))
```

But this does not work server-side, as `push` is not defined.
Am I missing something here? How can I issue navigation events via a Redux action just like above, but server-side?

Thanks a lot for your help.

**Comment by timdorr** [comment]
What do you mean push is not defined? A memory history will have that method available. You are configuring your server-side history incorrectly.

**Comment by webdif** [comment]
Thank you @timdorr, you were right, history was not set up properly server-side.

My problem is not gone though:
* If I load the page on the URL `/foo/bar`
* And in the component of this route, I do: `store.dispatch(push('/foo'))`
* Then the URL is not redirected, the browser is still showing `/foo/bar` in the address bar.

Interrestingly, I can see in my serialize initial state the value `/foo` for `routing.locationBeforeTransitions.pathname`, as the redirection has happened in the store…
