### ISSUE TITLE
history module version can cause problems with react-router

### ISSUE THREAD

**Issue by pkosenko** [reactjs/react-router-redux#456]
Here's a cross post from react-router:  https://github.com/ReactTraining/react-router/issues/3857#issuecomment-247217775

I was having trouble with a version of react-router-redux that included a history@1.9.0 dependency.  It was causing the failure of the createHistory function in my code.  I had to removed the react-router-redux module and that solved the problem.  I haven't yet tried installing and working with react-router-redux@4.0.5 which I see includes history 2.0.0.  So I cannot tell whether the problem continues with THAT version of the history module.  react-router requires history 2.1.2

So this post is advisory.  You might want to look into upgrading to history 2.1.2.

**Comment by timdorr** [comment]
We have no hard dependencies on any version of history: https://github.com/reactjs/react-router-redux/blob/master/package.json

We only care that you have `listen` and the other history APIs. This library doesn't deal with the stuff that react-router depends on.
