### ISSUE TITLE
Cannot use sinon spy on actions exported from 'react-redux-router'

### ISSUE THREAD

**Issue by jamespedid** [reactjs/react-router-redux#458]
Hello, the method you have chosen to make the exports of the package makes them harder to spy on. I found that if you export an object with those methods on them, they are exported as getters, which makes them unable to be easily spied on. If you instead export them in the same manner that you export routerMiddleware, this will fix this.

Is this something you're willing to change? Or can you think of a workaround? (I can get by without spying on it if that needs to be.)

example of what doesn't work:

```
import * as reactRouterRedux from 'react-router-redux'
...
sinon.spy(reactRouterRedux, 'replace') //does not work with function exported as a getter.
```

**Comment by timdorr** [comment]
It's really an implementation detail of Babel and how it handles various export forms. This is an issue for IE too (which doesn't have getters).

However, why not spy on the store via a middleware and wait for those actions to be dispatched? That would be good for other actions as well.

**Comment by Billy-** [comment]
@timdorr that is a good approach for unit testing your own dispatches. But when it comes to third party modules, you really don't want to be testing the implementation details of that module (i.e the action that it creates), but rather just that your own code has called the third party module correctly. For that reason I have to say it would be much better if we could spy on the method itself.

**Comment by canvaspixels** [comment]
You can do something like this:
```
import * as reactRouterRedux from 'react-router-redux';
const replaceStub = sinon.stub();
sinon.stub(reactRouterRedux, 'replace', { get: () => replaceStub });
// call your method
expect(replaceStub).to.have.been.calledWith('/path');
```

**Comment by Billy-** [comment]
@timdorr May I ask why you deleted that comment? Correct me if I'm wrong, it seemed like a valid solution?

**Comment by timdorr** [comment]
I mean to lock this. This thread is too old. If we need to bring up something new, please open a new issue.
