### ISSUE TITLE
Router params is not update after "push" was execute 

### ISSUE THREAD

**Issue by iroy2000** [reactjs/react-router-redux#459]
We are using React Router, React Redux Router and hashHistory

Routes
```
  <Route path='/(:bookmark)' component={DemoApp}>
      <IndexRoute component={DefaultRouteHandler} />
      <Route path="*" component={DefaultRouteHandler} />
  </Route>
```

Somewhere in our code, user click an action and we  do the following

```
import { push } from 'react-router-redux'

export const setHash = (hash) => {
  const hashString = encodeURI(JSON.stringify(hash))
  return push(`/#/${hashString}`)
}
```

But somehow in our view, we didn't get the "params" after `push` above was execute. 

```
this.props.params.bookmark
```

And when I try something like this doc, my ownProps.params.bookmark is also undefined ...
https://github.com/reactjs/react-router-redux#how-do-i-access-router-state-in-a-container-component

Did I do something wrong here ?

Thsnks

**Comment by iroy2000** [comment]
Ok, figured that out, closing it.

**Comment by fes300** [comment]
@iroy2000  please share your solution before closing
