### ISSUE TITLE
How can i use react-router-redux without changing url

### ISSUE THREAD

**Issue by asicfr** [reactjs/react-router-redux#466]
Is there a way to use "react-router" and "react-router-redux" to keep the router in sync with the Redux store but without change the url ? 
Thx

**Comment by timdorr** [comment]
You need to use a memory history.

**Comment by asicfr** [comment]
It works ... thanx

**Comment by anandejju** [comment]
MemoryHistory  is not working when we button click, on working with <Link> , any example would be helpful.
