### ISSUE TITLE
@@router/LOCATION_CHANGE action REPLACE action?

### ISSUE THREAD

**Issue by ariesbrunetyson** [reactjs/react-router-redux#467]
Hi
I've notices at some point the actions '@@router/LOCATION_CHANGE' is triggered with 'REPLACE' which clears out the query and search parameters? Is there any way I can skip this?

FYI, I'm using React Router's Link component with query param during this navigation

**Comment by timdorr** [comment]
Your code is issuing a replace action somewhere. If the replaced location doesn't include the previous search, that's on you to accommodate.

**Comment by ariesbrunetyson** [comment]
@timdorr My Code doesn't have anything to do with this. I checked my code clearly. Control is passing to this line only once through [this line](https://github.com/ReactTraining/react-router/blob/master/modules/Link.js#L101) in React router when i tap on Link component in my app.. When it is passed without query it works fine but invoking the action with only "PUSH".. But when it is passed with query it is not working as expected and triggers 'Replace' immediately after "PUSH"

**Comment by nickbar86** [comment]
I also have exactly the same problem. There is no replace action being called from anywhere in my code

**Comment by savbace** [comment]
Experiencing the same issues. Somebody have any updates/workarounds on this?
