### ISSUE TITLE
push would change hash while browserHistory is being used

### ISSUE THREAD

**Issue by JeffOwOSun** [reactjs/react-router-redux#468]
This behavior only occurs with push action from react-router-redux. If I call react-router's push directly, the URL changes as expected.

VERSIONS:
react-router-redux: 4.0.5
react-router: 2.4.1
history: 3.0.0

**Comment by timdorr** [comment]
You must be passing the wrong history instance into react-router-redux. Maybe sure you're applying the right instance with the middleware.
