### ISSUE TITLE
Get access to the previous Route.

### ISSUE THREAD

**Issue by akhayoon** [reactjs/react-router-redux#470]
I am trying to make a conditional statement based on the previous route I was on.

I have access to the all the react-router-redux props in my component (history, location, route etc...), but I can't seem to see any information about the previous route.

I know it must be available somewhere, since in my actions I am able to use the goBack() function react-router-redux provides to go back, I just don't know where to find it.

**Comment by timdorr** [comment]
We don't store previous locations in state. This is a question for history or react-router.
