### ISSUE TITLE
Missing location object in containers

### ISSUE THREAD

**Issue by solomon23** [reactjs/react-router-redux#471]
My containers used to listen for query param changes by checking `componentWillReceiveProps` and checking next.location against the previous location.  It looks like after implementing this library I no longer have access to `state.location` in `mapStateToProps(state)`.  The instructions say to use `ownProps` but that only works for route containers, which aren't my only containers that care about locations.  Is there another method to detect url changes ?

**Comment by timdorr** [comment]
You shouldn't rely on the location stored by this library. It changes before any hooks or handlers have run, so you can lead to error prone code. Send the location down from your route components via props.
