### ISSUE TITLE
Delay after dispatching push(action) before changing route?

### ISSUE THREAD

**Issue by ChrisPenner** [reactjs/react-router-redux#473]
Hey folks! Thanks for this awesome tool! It's really nice to use!

My issue right now is that I'm writing a 'delete' button for some resources in my app, basically my code looks like this: (in redux-saga)

```javascript
yield call(deleteFetch)
yield put(push('/'))
yield put(deleteResourceFromStore())
```

`deleteResourcefromStore` will delete the items from the store, but the delete button is on the page of the resource itself, so if the delete succeeds on the server, then I redirect away from the resource's page, then remove it from the store.

The problem is that when I try and do this, I always get errors that React is trying to render some of the resources that were deleted (of course implying that I was still on the resource page when they were removed from the store).

If I add a delay, everything works fine:

```javascript
yield call(deleteFetch)
yield put(push('/'))
yield delay(300)
yield put(deleteResourceFromStore())
```

So I guess my question is, does the route change happen synchronously or not? Do I have any guarantee that the route change has taken place before I perform my next action? If not, is there any way to ease this use case?

Thanks!

**Comment by timdorr** [comment]
Route changes are always asynchronous. Hence we call the location in state "`locationBeforeTransitions`". This is a side effect of react router 2.x/3.0, which is built to support async stuff.

Adding a delay (I would think 0 would be sufficient) is really the best way around it right now.
