### ISSUE TITLE
你的demo代码，用webpack编译的时候出现了这个错误。

### ISSUE THREAD

**Issue by laisx** [reactjs/react-router-redux#474]
ERROR in ./app.js
Module build failed: SyntaxError: Unexpected token (16:8)

```
const reducer = combineReducers({
   ...reducers,
   ^
    routing: routerReducer
 })

```

**Comment by chentsulin** [comment]
You need a `babel-plugin-transform-object-rest-spread` in your `.babelrc` (if you are using babel-loader).
