### ISSUE TITLE
Compability with History v3

### ISSUE THREAD

**Issue by just-boris** [reactjs/react-router-redux#475]
React router v3 was released today. The new version also updates dependency for history package. Now it requires history@3.x.

Then it turns out, that history has [a breaking change](https://github.com/mjackson/history/blob/v3.0.0/CHANGES.md#300-0)
> Breakage: history.listen no longer calls the callback synchronously once. Use history.getCurrentLocation instead

We need to detect new version and handle it properly.

**Comment by xuqingkuang** [comment]
@timdorr I saw the PR was merged in 3 days before, but when will the new release will be publish ?
