### ISSUE TITLE
LOCATION_CHANGE action no longer fired when page loads with react-router@3.0.0

### ISSUE THREAD

**Issue by sunjay** [reactjs/react-router-redux#477]
Hi,
I had to rollback to react-router 2.8.1 because no location change action is being sent when the page loads when I use react-router 3.0.0. There must be some breaking change that is causing this because they bumped the major version number.

I'm using react-router-redux@4.0.6.

I think this is a bug because this used to work and stopped working with the latest major react-router release.

**Comment by timdorr** [comment]
This library does not yet work with 3.0. Please continue to use React Router 2.8.1 and waiting until the fixes from #476 are released.

**Comment by lunaryorn** [comment]
Just out of curiosity, because we stumbled over this issue as well:  Why is react-router not a dependency of react-router-redux?  

If there had been a `"react-router": "^2.0"` dependency here `yarn` wouldn't even have let us update to react-router 3.
