### ISSUE TITLE
Stop telling people to use @next

### ISSUE THREAD

**Issue by rattrayalex** [reactjs/react-router-redux#478]
```
$ npm dist-tag ls react-router-redux
latest: 4.0.6
next: 4.0.0-rc.2
```

It appears that `@next` is actually behind latest. Can the docs have references to `@next` scrubbed? 

It would probably also be nice to update `@next` to point to `latest` so that those trying to live on the cutting edge are able to catch up.

**Comment by timdorr** [comment]
Sure. A PR is the best way to handle this.

**Comment by rattrayalex** [comment]
Terrific! I hope to be able to do so today. 

Does seem a bit optimistic to close the issue already though 😉

**Comment by timdorr** [comment]
I already removed it from the readme. I don't see other references, but a PR can point them out if I missed anything.

**Comment by rattrayalex** [comment]
Ah, thanks very much Tim! 

I see now that you meant you wished I'd submitted a PR instead of an Issue in the first place – apologies. I'm not very familiar with the project so I wasn't sure if that was an appropriate move or not (perhaps there is an upcoming `@next` pointing to v5, for example). 

Cheers!

**Comment by SimenB** [comment]
`next` should probably be latest unless there's actually newer versions available, shouldn't it? It's still rc 2

**Comment by timdorr** [comment]
The 5.0 stuff is not close to complete, so I haven't published a testing or alpha release yet. I should have some time for it soon now that I've gotten some other obligations out of the way and React Router 4.0 dev seems to have calmed down slightly (less internal changes).

**Comment by rattrayalex** [comment]
Hah, I didn't even know there *was* a 5.0 in the works. You move fast!
