### ISSUE TITLE
mapStateToProps method only receive react-router params if use withRouter function

### ISSUE THREAD

**Issue by raelmax** [reactjs/react-router-redux#482]
I'm trying use react-redux-router and face with a problem, the "ownProps" parameter of mapStateToProps function don't receive react-router "params" attribute. To fix this we need to pass our "connect" function to react-router withRouter function.

Don't work:
```javascript
const VisibleTodoList = connect(
  mapStateToProps,
  mapDispatchToProps
)(TodoList)
```

Work:
```javascript
import { withRouter } from 'react-router';
const VisibleTodoList = withRouter(connect(
  mapStateToProps,
  mapDispatchToProps
)(TodoList))
```

I think we need update the documentation with this information:
https://github.com/reactjs/react-router-redux#how-do-i-access-router-state-in-a-container-component

Thanks.

**Comment by timdorr** [comment]
This library doesn't sync router params because it only interacts with history. You should use a separate route component if you need access to the params. It can shove them into the store in its constructor or cWM.
