### ISSUE TITLE
Consider adding more specific actions for location changes

### ISSUE THREAD

**Issue by joelmukuthu** [reactjs/react-router-redux#484]
In addition to `LOCATION_CHANGE`, would it be possible to add more specific identifiers for a location change, such as `PATHNAME_CHANGE`, `QUERY_CHANGE` etc?

I've made an attempt at this using a redux middleware which dispatches a custom action on detecting pathname changes. While it works, it's not reliable since things like changing the order of the actions has some undesirable side effects on the back/forward browser history. It would be better if that was offered by this module.

**Comment by timdorr** [comment]
I don't see why you would want to do this. If your state changes depending on a particular property, then you can use a selector to only watch that section of the location descriptor.

**Comment by joelmukuthu** [comment]
Well in most cases when the `query` bit of a location descriptor changes it means the user is still on the same page (for instance on a search page), while a change in the `pathname` means they navigated away from that page. There are use cases for wanting to differentiate between the two cases. For instance, if you show UI errors in a "global" component you might want to clear errors relating to the page the user was on when they navigate away from that page. 

In order to figure out if only the pathname was changed inside a reducer, you would need `store.getState` to get `locationBeforeTransitions`, which unless I'm mistaken, you don't.
