### ISSUE TITLE
LOCATION_CHANGE causes replace after push

### ISSUE THREAD

**Issue by nickbar86** [reactjs/react-router-redux#489]
i resubmit the question cause i experience the same issue as in #467 . My Code doesn't have anything to do with this. I checked my code clearly. Control is passing through this line in React router only once when i tap on Link component in my app.. When it is passed without query it works fine but invoking the action with only "PUSH".. But when it is passed with query it is not working as expected and triggers 'Replace' immediately after "PUSH"

**Comment by tengis** [comment]
same problem

**Comment by oyeanuj** [comment]
@nickbar86 @tadeuzagallo did any of you find a solution to this?
