### ISSUE TITLE
Error with history v4.x: history.getCurrentLocation is not a function 

### ISSUE THREAD

**Issue by bertho-zero** [reactjs/react-router-redux#491]
Since the last update for history support 3 I have the following error if I use history 4:

`TypeError: history.getCurrentLocation is not a function`

from sync.js line 108:
```js
// support history 3.x
if (history.getCurrentLocation) {
  handleLocationChange(history.getCurrentLocation());
}
```

**Comment by timdorr** [comment]
We don't support history 4.0 in this library.

**Comment by bertho-zero** [comment]
I think we need a change like this:

```js
// support history 3.x
const currentLocation = typeof history.getCurrentLocation === 'function' ? history.getCurrentLocation() : history.location;
handleLocationChange(currentLocation);
```

**Comment by 6a68** [comment]
> We don't support history 4.0 in this library.

@timdorr Sorry, why is that? Are you never planning to bump major versions?

**Comment by timdorr** [comment]
React Router doesn't support history 4.0. It uses it in React Router 4.0, but that is not yet released and will be a complete rewrite for this library.
