### ISSUE TITLE
Add ability to get URL params in reducer.

### ISSUE THREAD

**Issue by smaye81** [reactjs/react-router-redux#492]
Currently there is no way to access the URL params on props in the reducer.  For example a URL / Route of:  `/users/:id/prefs`.  I would like to be able to get the value of `id` from the store.  Not sure if this is even possible or if this is on the part of react-router, but figured I'd start here.

**Comment by timdorr** [comment]
This has been asked multiple times. We cannot do it because we don't integrate with react-router directly, just history.
