### ISSUE TITLE
TypeError: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by ideal-life-generator** [reactjs/react-router-redux#493]
When I use more flexible middlewares, like redux-thunk, I can return `undefined` in end of action. Then I have `routerMiddleware` error in:
```
if (action.type !== _actions.CALL_HISTORY_METHOD) {
```
```
TypeError: Cannot read property 'type' of undefined
```

I think you need ignoring `undefined` or different not standard actions returning. Here is example of action:

```
export function checkStoredUser() {
  const refreshToken = cookie.load('refresh-token');
  const token = cookie.load('token');

  if (token || refreshToken) {
    setDefaultHeader('Authorization', token);

    return async (dispatch) => {
      dispatch(setStored());

      await dispatch(me());
    };
  }

  return undefined;
}
```

I think is normal for redux, because I don't have the same problems with other soft.

```
if (action && action.type === _actions.CALL_HISTORY_METHOD) {
...
} else {
  next(action);
}
```

**Comment by timdorr** [comment]
You just have to order your middleware correctly. Make sure redux-thunk is first.

**Comment by ideal-life-generator** [comment]
If I don't use redux-thunk is also throw this error.

**Comment by timdorr** [comment]
You are doing something wrong if you're passing in an action that is not an object with a type field, and you don't have a middleware set up to handle that. We expect a type field, the same as redux does: https://github.com/reactjs/redux/blob/master/src/createStore.js#L157-L162

**Comment by ideal-life-generator** [comment]
I'm sorry, you right)
