### ISSUE TITLE
React-router-redux consumes its actions

### ISSUE THREAD

**Issue by char0n** [reactjs/react-router-redux#501]
Hi There,

I was wondering if there is a reason why the middleware is consuming the action instead of returning it ?

Here is the link of code in question:

https://github.com/reactjs/react-router-redux/blob/master/src/middleware.js#L15

According to the redux docs dispatch should always return dispatched action whatever it could be (usually an object). Maybe there a is a valid reason not to return it, but I cannot figure it out. 

Thanks for any answer

http://redux.js.org/docs/api/Store.html#dispatch

**Comment by timdorr** [comment]
Because this is simply a hack to proxy calls over to the history object. We don't want it to end up in the store.

**Comment by char0n** [comment]
@timdorr thx for info
