### ISSUE TITLE
Wrapped history doesn't get updated

### ISSUE THREAD

**Issue by ForsakenHarmony** [reactjs/react-router-redux#502]
if you wrap the history with `syncHistoryWithStore` it doesn't get updated anymore because you copy it [here](https://github.com/reactjs/react-router-redux/blob/master/src/sync.js#L107) 

This prevents a router that doesn't use `history.listen` from being able to get the correct value

**Comment by timdorr** [comment]
What router doesn't use history.listen? That's kind of critical to how React Router works.

**Comment by ForsakenHarmony** [comment]
preact-router

**Comment by ForsakenHarmony** [comment]
Also i.e. history.location should still get updated

**Comment by timdorr** [comment]
You need to pass in the history instance you get back from the syncHistoryWithStore function into your router.

**Comment by ForsakenHarmony** [comment]
`history.location` doesn't even get updated in the wrapped history

**Comment by ForsakenHarmony** [comment]
maybe something like this instead of the current return statement

https://hastebin.com/hevivahaxi.js

**Comment by ForsakenHarmony** [comment]
https://hastebin.com/ucisiyidus.js something like this fixes it

**Comment by ForsakenHarmony** [comment]
can you please reopen this at least?

**Comment by ForsakenHarmony** [comment]
https://github.com/reactjs/react-router-redux/pull/504
