### ISSUE TITLE
Minimizing Bundle Size

### ISSUE THREAD

**Issue by jacobgreen25** [reactjs/react-router-redux#503]
React Router offers the ability to reduce our bundle size by doing the following

https://github.com/ReactTraining/react-router/blob/master/docs/guides/MinimizingBundleSize.md

Would it be possible to do this for react-router-redux? Would it offer enough of a file size reduction for it to be worth the effort?

**Comment by jacobgreen25** [comment]
It looks like the minified dist file is about 4KB. Wouldn't make much sense to try to split that out to maybe save 1-2KB.

**Comment by timdorr** [comment]
Simply import the parts you need individually. Keep in mind after minification and gzip, this library is rather small by comparison to React Router itself.
