### ISSUE TITLE
handleStoreChange history.transitionTo PUSH shouldn't it be history.replace?

### ISSUE THREAD

**Issue by Xesenix** [reactjs/react-router-redux#513]
__I have created middleware that changes action object while listening for LOCATION_CHANGE action.type.__ But that results in breaking of history navigation due to pushing new state to history after each browser url change. __When I click few times on browser history back button it loops itself on current and previous url.__

I have found that syncHistoryWithStore is adding listener handleStoreChange on store change that is run when you navigate with use of browser history navigation buttons and pushes new history states every time url changes.
I have replaced it:
original src/sync.js:
```
  history.transitionTo({
    ...locationInStore,
    action: 'PUSH'
  })
```
my fixed version:
```
  history.transitionTo({
    ...locationInStore,
    action: 'REPLACE'
  })
```
__This fragment is called when you use devTools so I think it shouldnt add new history states or am I wrong?__
I know that i can use adjustUrlOnReplay = false to fix looping navigation but then I lose url updates on devTools navigation.

And here is simplified version of my middleware history and store that can cause this problem:
```
// middleware
import { LOCATION_CHANGE } from 'react-router-redux'
const middleware = store => next => action => {
  if (action.type === LOCATION_CHANGE) {
    next({
      type: 'TEST'
    })
  }
  return next(action)
}

// reducer
import { combineReducers } from 'redux'
import { routerReducer as routing } from 'react-router-redux'
const reducer = combineReducers({
  routing
})

// store
import { compose, applyMiddleware, createStore } from 'redux'
import DevTools from './containers/dev-tools'
import reducer from './reducers'
const configureStore = (preloadedState) => {
  const store = createStore(reducer, preloadedState, compose(
    applyMiddleware(middleware),
    DevTools.instrument()
  ))
  return store
}
const store = configureStore(preloadedState)

// history
import { syncHistoryWithStore } from 'react-router-redux'
import { useRouterHistory } from 'react-router'
import createBrowserHistory from 'history/lib/createBrowserHistory'

const createAppHistory = useRouterHistory(createBrowserHistory)
const history = createAppHistory({ basename: process.env.PUBLIC_URL })
const appHistory = syncHistoryWithStore(history, store, { adjustUrlOnReplay: true })//kind of works with false

// some simple react component with routing
render(<Root store={store} history={appHistory}/>, document.getElementById('app'))

```

**Comment by timdorr** [comment]
The history of your navigations should remain immutable, regardless of what the dev tools is doing to the store and therefore your browser's URL bar. Replacing the URL means dropping the previous location, which means you lose access to it if you need some information from it (such as `location.state`).

**Comment by Xesenix** [comment]
If you have situation described above without my fix clicking back button in browser adds new history item and therefor if you do it second time you end in loop between two last history items.
And if you navigate with devtools info about your current state should be provided by redux store you wont loose location.state because it should be repopulated when you get back to last redux action state.
