### ISSUE TITLE
onLeave is called when changing params

### ISSUE THREAD

**Issue by michelalbers** [reactjs/react-router-redux#514]
The ```onLeave``` hook of the route is called when changing params of a route.

Given the following route config:

```JavaScript
{
  name: 'profile',
  path: '/profile/:username',
  onLeave() { /* ... */ }
}
```

Changing from ```profile/foo``` to ```profile/bar``` will call ```onLeave```. Is this intentional?

**Comment by timdorr** [comment]
This is a react-router issue, if anything. This doesn't have to do with this library.
