### ISSUE TITLE
react router v4 and history v4

### ISSUE THREAD

**Issue by GuillaumeCisco** [reactjs/react-router-redux#520]
Hello and thank you for this amazing project.

I was trying to use react-router-redux with react router v4 and history 4.x.
It hardly works!
Only problem I came through is `syncHistoryWithStore`. It seems like this method is no more adapted to the history 4.x code. So I add to disable it for now. An override to verify.

But `routerReducer` and `routerMiddleware` works well.
I just used my history object as :
```javascript
import {createHashHistory} from 'history';

const history = createHashHistory();

export default history;
```

No more.
And using react-router with :
```javascript
import {Router} from 'react-router';
import history from '../history';

<Router history={history}>
    ... routes ...
</Router>
```

Hope it will help for future portability.

EDIT: One hint is in version v4.0.0.0-2, history removed history.getCurrentLocation().
`syncHistoryWithStore` works with it so I think we could dig here :)

**Comment by timdorr** [comment]
We don't support v4 yet.

**Comment by GuillaumeCisco** [comment]
@timdorr, yeah I know, that's why I opened this issue.
Why closing it?
Your don't plan to support it?

**Comment by timdorr** [comment]
We will support it eventually. However, it isn't out of beta yet, so I don't want to try and hit a moving target.

**Comment by GuillaumeCisco** [comment]
Hey @timdorr, I've just created a PR for supporting react-router v4 with history v4 : https://github.com/reactjs/react-router-redux/pull/522

Hope you'll review it and enjoy it ;)
