### ISSUE TITLE
Server Rendering: history.getCurrentLocation key causes invariant

### ISSUE THREAD

**Issue by michaelBenin** [reactjs/react-router-redux#528]
In src/sync, when calling:
```js
history.getCurrentLocation()
```
This yields different results from client and server, hence invariant errors upgrading from 4.0.6 to 4.0.7 and 4.0.8.

On server:
```js
{ pathname: '/repo/michaelBenin/react-ssr-spa',
  search: '',
  hash: '',
  state: undefined,
  action: 'POP',
  key: null,
  query: {} }
```
Where as in browser, key has a value of a string and not null.

First reported here: https://github.com/reactjs/react-router-redux/issues/481#issuecomment-272557422 but wasn't fixed in 4.0.8

**Comment by michaelBenin** [comment]
A fix I've tested in sync.js

```
  // History 3.x doesn't call listen synchronously, so fire the initial location change ourselves
  if (history.getCurrentLocation) {
    var handleChangeLocation = history.getCurrentLocation();
    handleChangeLocation.key = null;
    handleLocationChange(handleChangeLocation);
  }
```

I want to know why the key generation logic would be always null on server though. Unfortunately I'm under a tight deadline at work and we are still using 4.0.6.

**Comment by michaelBenin** [comment]
Also, it looks like this method has been removed in the later versions of the history library: 

https://github.com/ReactTraining/history/blob/22a2f4d31f7bb74027afae8ea624fdb82730e5c5/CHANGES.md#v400-2

**Comment by timdorr** [comment]
[I already mentioned that the initial POP is supposed to be null](https://github.com/reactjs/react-router-redux/issues/481#issuecomment-272878348):
> That initial null key is described in the 3.0 changelog: https://github.com/mjackson/history/blob/v3.x/CHANGES.md#300-0

Also, what error are you triggering?

**Comment by michaelBenin** [comment]
Invariant issue, specifically on routing in state.

**Comment by timdorr** [comment]
What *specific* error are you triggering?

**Comment by michaelBenin** [comment]
```
Uncaught Error: You're trying to render a component to the document using server rendering but the checksum was invalid. This usually means you rendered a different component type or props on the client from the one on the server, or your render() methods are impure. React cannot handle this case due to cross-browser quirks by rendering at the document root. You should look for environment dependent code in your components and ensure the props are the same client and server side:
 (client) action":"POP","key":"8fyrvj","query":{}}
 (server) action":"POP","key":null,"query":{}}},"c
    at invariant (invariant.js:38)
    at Object._mountImageIntoNode (ReactMount.js:504)
    at mountComponentIntoNode (ReactMount.js:112)
    at ReactReconcileTransaction.perform (Transaction.js:140)
    at batchedMountComponentIntoNode (ReactMount.js:126)
    at ReactDefaultBatchingStrategyTransaction.perform (Transaction.js:140)
    at Object.batchedUpdates (ReactDefaultBatchingStrategy.js:62)
    at Object.batchedUpdates (ReactUpdates.js:97)
    at Object._renderNewRootComponent (ReactMount.js:320)
    at Object._renderSubtreeIntoContainer (ReactMount.js:401)
    at render (ReactMount.js:422)
    at index.js:50
    at match.js:67
    at createTransitionManager.js:99
    at done (AsyncUtils.js:79)
    at AsyncUtils.js:85
```

**Comment by timdorr** [comment]
The browser history will [pull from `window.history.state`](https://github.com/ReactTraining/history/blob/v3.x/modules/BrowserProtocol.js#L31), which may be the problem here. I assume you're refreshing the page when you get that error? What happens if you open a new tab and load up the page?

Note that this is a `history` bug, not something we're doing wrong. I would open up an issue over there to get it fixed.

*However*, just looking through your code here, you're trying to render the initial Redux state inside of a component that also exists in the client. You shouldn't be doing that, as it's not needed on the client side. You should render your React client into a root DOM node that doesn't contain that state data, which won't be used after the initial loading. See our example here for one way to do that: https://github.com/reactjs/react-router-redux/blob/master/examples/server/server.js

**Comment by michaelBenin** [comment]
When is it planned to upgrade the history dependency in this project?

**Comment by timdorr** [comment]
That doesn't have anything to do with the problem you're running into. The same thing will happen with history 4, but React Router 3.x isn't compatible with that version anyways.
