### ISSUE TITLE
Example of server side rendering setup

### ISSUE THREAD

**Issue by willdembinski** [reactjs/react-router-redux#532]
Its amazing that there isnt a good example thats immediately available for Node.

There's a rails example provided in the Docs - but that doesnt help people trying to get up and running quickly.  Could we get one?

**Comment by timdorr** [comment]
This is literally one of our two examples: https://github.com/reactjs/react-router-redux/tree/master/examples/server

**Comment by willdembinski** [comment]
Timdorr - you're awesome for even taking the time to reply.

I have no excuse other than frustration was blinding me.  I am one of the worst types of people on the internet.

Thank you very much.
