### ISSUE TITLE
TypeScript error when using hashHistory

### ISSUE THREAD

**Issue by WaSa42** [reactjs/react-router-redux#533]
TypeScript catch an error when using hashHistory in `routerMiddleware`.
`error TS2346: Supplied parameters do not match any signature of call target.`

And from the IDE:
`Argument of type 'History' is not assignable to parameter of type 'History'. Property 'length' is missing in type 'History'`

``` javascript
/* ROUTER */
import { hashHistory } from 'react-router'
import { routerMiddleware, syncHistoryWithStore } from 'react-router-redux';

/* MIDDLE WARES */
const middleWares = [thunkMiddleware, routerMiddleware(hashHistory)];
```

What should I do ?

Thanks for all the work here.

**Comment by timdorr** [comment]
This isn't a bug in this library. If you're having problems with history typings, you should go to the project wherever those came from (Definitively Typed or somewhere else).
