### ISSUE TITLE
syncHistoryWithStore does not respect redux state

### ISSUE THREAD

**Issue by pronebird** [reactjs/react-router-redux#534]
Hi,

I am trying to restore the displayed page on app startup but it's always `/`, redux store is preloaded from local storage. How do you tell `syncHistoryWithStore` to stop erasing route information?

I use `redux-localstorage` to persist redux to local storage.

```js
import { routerMiddleware, routerReducer as routing } from 'react-router-redux';
import persistState from 'redux-localstorage';
import thunk from 'redux-thunk';
import routes from './routes';

const router = routerMiddleware(hashHistory);

const reducers = {
  routing
};

const middlewares = [ thunk, router ];

function configureStore(initialState) {
  const enhancer = compose(applyMiddleware(...middlewares), persistState());
  const rootReducer = combineReducers(reducers);
  
  return createStore(rootReducer, initialState, enhancer);
}

const initialState = {};
const store = configureStore(initialState);
const routerHistory = syncHistoryWithStore(hashHistory, store);

ReactDOM.render(
  <Provider store={ store }>
    <Router history={ routerHistory } routes={ routes } />
  </Provider>,
  rootElement
);
```

I tried `adjustUrlOnReplay` without luck:

```js
const routerHistory = syncHistoryWithStore(hashHistory, store, { adjustUrlOnReplay: true });
```

Thanks

**Comment by pronebird** [comment]
Debugging through syncHistoryWithStore reveals that the following statement breaks:

```js
if (currentLocation === locationInStore || initialLocation === locationInStore) {
        return;
}
```

in my case `initialLocation` restored from state and is '/connect' and is the same as `locationInStore`, therefore `syncHistoryWithStore` does not attempt to restore the location. 

```js
// Init initialLocation with potential location in store
initialLocation = getLocationInStore();
```

**Comment by pronebird** [comment]
As a workaround we could simply enforce the transition to new route right after `syncHistoryWithStore`. Since `syncHistoryWithStore` will always reset the route to '/', we could inspect the store prior to calling it and save last visited location and then feed it back after creating `routerHistory`:

```js
const recentLocation = (store.getState().routing || {}).locationBeforeTransitions;
const routerHistory = syncHistoryWithStore(hashHistory, store, { adjustUrlOnReplay: true });
if(recentLocation && recentLocation.pathname) {
  routerHistory.replace(recentLocation.pathname);
}
```

**Comment by rob2d** [comment]
Just a random note, it seems the syncHistoryWithStore method isn't a necessity in v5.0.0 as the middleware takes care of it. So perhaps if migrating to the alpha for that, no more issues? [outside of... the alpha thing]

**Comment by MacKentoch** [comment]
It seems like react-router-redux v5.0.0 will fix a lot of things when using react-router 4.
But what about using immutable state, will a custom routerReducer do the job:
```javascript
import { fromJS }           from 'immutable';
import { LOCATION_CHANGE }  from 'react-router-redux';

const initialState = fromJS({
  locationBeforeTransitions: null
});

export default (state = initialState, action) => {
  if (action.type === LOCATION_CHANGE) {
    return state.set('locationBeforeTransitions', action.payload);
  }

  return state;
};

```

Or middleware will take care of it?

**Comment by mentrie** [comment]
@MacKentoch have you gotten a workaround for your question ☝️

**Comment by MacKentoch** [comment]
@mentrie I ended my starter with react-router-redux 4.x.x and [wrote my own reducer](https://github.com/MacKentoch/react-redux-immutable-webpack-ssr-starter/blob/master/src/app/redux/modules/immutableRoute.js).

I did not give a try to 5.x since I did have the use case in private or pro project then.

But, I keep interesting in new about it
