### ISSUE TITLE
push() with params

### ISSUE THREAD

**Issue by Gtosta96** [reactjs/react-router-redux#539]
Hello, I'm trying to dispatch push function with extra params, but I dont receive this data in reducers...  have someway to do it?

code bellow:
`dispatch(push('someURL', { somedata: 'data' }));`

**Comment by timdorr** [comment]
This specific use case [is tested](https://github.com/reactjs/react-router-redux/blob/master/test/actions.spec.js#L31), so it sounds like you have something set up wrong. Make sure you have the middleware connected right and in the correct order.

**Comment by Gtosta96** [comment]
Hi @timdorr sorry for few details in previous post.

When I use *push* method from *react-router-redux* it triggers **@@router/CALL_HISTORY_METHOD** action, but I can't intercept it from my reducers (I don't know why), and after it, auto-triggers **@@router/LOCATION_CHANGE**, but when I receive it, I don't receive the params passed in *push* method. 

To be clear, follow the imgs bellow:
![1](https://cloud.githubusercontent.com/assets/11162653/23340543/ed02a8da-fc16-11e6-8cd9-ebaa9cb62a84.jpg)
I can retrieve *redirect* in this one through *query*. :)

![2](https://cloud.githubusercontent.com/assets/11162653/23340575/6d5d3f04-fc17-11e6-803c-87d5e43052ea.jpg)
I can't retrieve *somewhere* or *{ some: 'value'}* in this one. :(

Have someway to pass data just like in second image?

Thank you, and sorry for my bad english!

**Comment by timdorr** [comment]
That's not the signature of the `push` method: https://github.com/ReactTraining/history/blob/v3/docs/GettingStarted.md#navigation

You're probably wanting to put that extra data on the location's `state`.
