### ISSUE TITLE
LOCATION_CHANGE on page load

### ISSUE THREAD

**Issue by xtrinch** [reactjs/react-router-redux#543]
I cannot get location_change to fire on page load. I am using react-router-redux 4.0.8, react-router 3.0.2 with react-boilerplate 3.3.3.

**Comment by NMFR** [comment]
Could this be what you are after https://github.com/reactjs/react-router-redux/issues/531 ?

I was just researching that problem.

**Comment by xtrinch** [comment]
I don't think so, as I've had the same issue with version 4.0.6 and 4.0.7. I've only upgraded to 4.0.8 because I thought it would fix the issue

**Comment by timdorr** [comment]
You shouldn't be getting this action. The location hasn't changed when you're loading the page.
