### ISSUE TITLE
Multiple actions not possible

### ISSUE THREAD

**Issue by cmjartan** [reactjs/react-router-redux#544]
Hi, in our app, we have a scenario where we need to do something like this in one step:
```
dispatch(go(-2))
dispatch(replace('/new/url'))
```
Currently we don't see a way to do that with `react-router-redux`. If we execute that code, we do not reach `/new/url`. In redux dev tools I can se that the second LOCATION_CHANGE action is dispatched before the first one.
  
Is there some way to achieve this, maybe as workaround by manipulating history another way?

**Comment by timdorr** [comment]
Your code is likely being short circuited. Doing a history "transaction" isn't something it supports itself. You would have to do this kind of thing in your own code:
```js
let nextAction

if (something) nextAction = go(-2)
if (somethingElse) nextAction = replace('/new/url')

dispatch(nextAction)
```
