### ISSUE TITLE
Does not work with thunk

### ISSUE THREAD

**Issue by drunkengranite** [reactjs/react-router-redux#545]
Dispatching a push inside of a thunk action does not change the state. More specifically it changes for an instant then reverts.

**Comment by timdorr** [comment]
Make sure you have your middleware ordered correctly. The thunk middleware will need to go first so that it can handle functions as actions.

**Comment by godd9170** [comment]
@timdorr Can you provide an example of how you apply react-redux-router with thunk?

**Comment by Jman495** [comment]
In case anyone else is stuck, I found [this](https://medium.com/@notrab/getting-started-with-create-react-app-redux-react-router-redux-thunk-d6a19259f71f) guide that helped 

Relevant portion about applying react-router-redux middleware with redux thunk:

`const middleware = [
  thunk,
  routerMiddleware(history)
]`
