### ISSUE TITLE
LOCATION_CHANGE after page refresh

### ISSUE THREAD

**Issue by fantua** [reactjs/react-router-redux#548]
`LOCATION_CHANGE` action is fired after page refresh, that is how it should be?

**Comment by timdorr** [comment]
Yup

**Comment by fantua** [comment]
@timdorr how can I clear location `state` after page refresh?

**Comment by timdorr** [comment]
The page has some sort of location when you load/refresh a page. It wouldn't make sense to have no location.

**Comment by fantua** [comment]
I'll try to explain more correct.

I'm dispatching `push` action with `state`:
```js
dispatch(push({
    pathname: '/index',
    state: {
        message: 'hello'
    }
}));
```

And in reducer I listen `LOCATION_CHANGE`:
```js
case LOCATION_CHANGE: {
    const { message } = action.payload.state;

    return {
        ...state,
        message
    };
} 
```

But after page refresh I alway got `message` in `location.state`, how can I clear that?

**Comment by timdorr** [comment]
Something else is restoring that state. That is cleared when refreshing, much like the pinterest modal example from RR.

**Comment by fantua** [comment]
Refreshed: 
![img](http://image.prntscr.com/image/11ce5fb6e729485786f64cb2b6869c6f.png)

**Comment by fantua** [comment]
@timdorr is that a bug, because state isn't cleared?

**Comment by timdorr** [comment]
We aren't persisting state. Something else is keeping it around after refreshing the page.

**Comment by fantua** [comment]
But who can do that?
