### ISSUE TITLE
syncHistoryWithStore does not update location property while listening

### ISSUE THREAD

**Issue by wzuo** [reactjs/react-router-redux#552]
While subscribing to history API location property on returned object should be changed. Currently router does not react on this change. Following snippet seems to fix that issue:

```javascript
    const history = syncHistoryWithStore(browserHistory, store, {
      selectLocationState: createSelectLocationState(),
    });
    const oldListenFn = history.listen;
    history.listen = (listener) => {
      const proxyListener = (location) => {
        if (location) {
          history.location = location; // here magic patching occurs
        }
        return listener(location);
      }
      return oldListenFn(proxyListener);
    };
```

**Comment by timdorr** [comment]
I'm not sure what you're attempting to do, but I would grab the listen method before sync with the store, as [we overwrite it ourselves](https://github.com/reactjs/react-router-redux/blob/master/src/sync.js#L109-L139).

**Comment by wzuo** [comment]
In code you posted the new object is returned - which is not history from browser, therefore location property is not updated while URL in browser changes, even if in original object it does. This causes react-router to not work properly, since it bases on value of that property.
