### ISSUE TITLE
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

### ISSUE THREAD

**Issue by comerc** [reactjs/react-router-redux#562]
"react-router-redux": "next"

![2017-04-15 20 54 38](https://cloud.githubusercontent.com/assets/1025241/25065764/d7fc80e6-221d-11e7-9991-cebdf13a22e1.png)

**Comment by timdorr** [comment]
Wrong repo. Make sure you've updated to the latest alpha.

**Comment by richburdon** [comment]
@timdorr what do you mean wrong repo (I'm having the same issue, but I can't tell which of the half dozen react-* packages is causing it). I'm using react-router-redux 4.0.8. Is the fix only in "alpha"?

**Comment by timdorr** [comment]
4.0 doesn't use React at all, so it's not the cause and there's nothing to fix.
