### ISSUE TITLE
Uncaught TypeError: (0 , _reactRouterRedux.syncHistoryWithStore) is not a function

### ISSUE THREAD

**Issue by mvinet** [reactjs/react-router-redux#564]
Hi i have a problem :
Uncaught TypeError: (0 , _reactRouterRedux.syncHistoryWithStore) is not a function

this is my code :

const store = createStore(
    combineReducers({
        testReducer,
        routing: routerReducer
    })
)

const history = syncHistoryWithStore(browserHistory, store);

any idea ?

i use version : "react-router-redux": "^5.0.0-alpha.6",

thanks and sorry for my english..

**Comment by timdorr** [comment]
You installed the wrong version. Install 4.0.8.

**Comment by mvinet** [comment]
ho ok, i just installed the default version with npm .. thanks.

**Comment by missgrizzly** [comment]
I have 4.0.8 installed and I also see this problem
