### ISSUE TITLE
Component Imbrication gone ?

### ISSUE THREAD

**Issue by lucasriondel** [reactjs/react-router-redux#565]
Hi, 

I wanted to be sure, but is component imbrication gone with 5.0.0 ? 

```js
<Route path="/" component={App}>
  <IndexRoute component={FormLogin} />
  <Route path="register" component={FormRegister}/>
</Route>
```

I wanted to know why you decided to remove it, and if it possible to have it again using a trick.

**Comment by timdorr** [comment]
I've never heard the term "imbrication" before (in the context of React Router). I assume you mean nested paths? In which, yes, that's gone. 

You should read through all the documentation from scratch. The entire API for React Router has changed.

**Comment by lucasriondel** [comment]
Why was it removed ? It was a great feature ! It's sad that it is not possible anymore.. :/
