### ISSUE TITLE
@@router/LOCATION_CHANGE triggered twice using push

### ISSUE THREAD

**Issue by zhenyulin** [reactjs/react-router-redux#570]
I'm currently creating navigation with redux actions with setting of `routerMiddleware(hashHisotry)`.

The navigation action creator was bound to a button, when on click it triggers `dispatch(push(${certainLocation}))`.

In Redux Dev Tools, I found that every click on the button will trigger two `@@router/LOCATION_CHANGE` actions, first one with the `action: 'PUSH'`in the payload, and second one with `action:'POP'` in the payload. Since I haven't found documents or hints on StackOverflow, I decide to put it here to check what's creating this abnormal behaviour here. It is currently polluting the analytics.

I'm using `redux-segment` to integrate the analytics tracking, which shall support `react-router-redux` out of box. However the `path` is not properly recognised and it works fine with a manual page event setup in the tracker.

**Comment by timdorr** [comment]
This is a known bug with hash history. You have to use browser or memory history instead: ReactTraining/history#427
