### ISSUE TITLE
Readme suggestion

### ISSUE THREAD

**Issue by danielo515** [reactjs/react-router-redux#572]
Hello,

This part of the documentation helped me a lot:

> What if I want to issue navigation events via Redux actions?
> 
> React Router provides singleton versions of history (browserHistory and hashHistory) that you can import and use from anywhere in your application. 

Because I needed the action creators to be able to redirect from redux sagas. As you said, I was using browserHistory before. However, because I had to override the browser history (to include a basic path) I can no longer use the browserHistory singleton. But, using the action creator to push a route change worked perfectly. My suggestion, is that you can include one small comment after the `However, if you prefer Redux style actions, ` sentence. Something like "(this may be useful if your have your browserHistory overriden)" or something like that.

I am a bit new to redux and redux-route and this took me a while to figure out.

Regards

**Comment by timdorr** [comment]
A PR would be the best way to handle this, so we can discuss specifics.
