### ISSUE TITLE
How to remove Console Messages ?

### ISSUE THREAD

**Issue by chandan7193** [reactjs/react-router-redux#575]
![screenshot from 2017-05-12 10-31-09](https://cloud.githubusercontent.com/assets/22831737/25985879/988aacce-370a-11e7-89d5-4c33e17628cb.png)
How can I remove this messages from the console? console shows this message on the live website as well.

**Comment by rockingskier** [comment]
It looks like you have the [redux-logger](https://github.com/evgenyrodionov/redux-logger) installed.  Remove that from your middleware and you should be message free.

Alternatively [only enable](https://github.com/evgenyrodionov/redux-logger#log-only-in-development) it in development.
