### ISSUE TITLE
"LOCATION_CHANGE" dispatch twice

### ISSUE THREAD

**Issue by lama-pacos** [reactjs/react-router-redux#578]
When I use a hashHistory, LOCATION_CHANGE will dispatch twice.

example:

```
user/xxx => user/xxx/#
```

i think the following code causes it

```
  if (history.getCurrentLocation) {
    handleLocationChange(history.getCurrentLocation())
  }
```

**Comment by timdorr** [comment]
https://github.com/reactjs/react-router-redux/issues/570#issuecomment-297783172
