### ISSUE TITLE
react-router-redux sync history with store broke navigation through dispatched actions

### ISSUE THREAD

**Issue by carloluis** [reactjs/react-router-redux#581]
using `react-router-redux` push to change url through `redux` while wrapping history (browserHistory) with syncHistoryWithStore doesn't work.

the problem arises because the syncHistoryWithStore returns a new history object, therefore the history used for creating the redux store (in routerMiddleware) does not match with the one used in the routing (this one has a dependency to the store: `syncHistoryWithStore(browserHistory, store)`

Example: 

```javascript
// history.js
import { createBrowserHistory } from 'history';
export defaulr createBrowserHistory();

// store.js
import { routerReducer, routerMiddleware } from 'react-router-redux';
import { createStore, applyMiddleware, combineReducers } from 'react-redux'
import browserHistory from './history';

const store = createStore(
    combineReducers({ 
        // ...reducers,
        routing: routerReducer 
    }),
    applyMiddleware(
      // ...middlewares,
      routerMiddleware(browserHistory)
    )
  );

export default store;

// routes.js
import { syncHistoryWithStore, push }  from 'react-router-redux';
import { Router, Switch, Route } from 'react-router-dom';
import { Provider } from 'react-redux';
import history from './history';
import store from './store';

const browserHistory = syncHistoryWithStore(history, store); // sync func. returns new instance of `history`
browserHistory.listen(location => console.info('-> location:', location));

const Store = (
   	<Provider store={store}>
		<Router history={browserHistory}>
			<Switch>
				<Route exact path="/" component={Home} />
				<Route path="/about" component={About} />
			</Switch>
		</Router>
	</Provider>
);

// render to dom...

// expected result: the browser renders the /About page
store.dispatch(push('/about')); 
// but, the previous line only changes the url 
// not the store, neither the component tree 
```

A solution for this issue could be found [in this fork](https://github.com/carloluis/react-router-redux/tree/fix/sync-history)
The commit change [here](https://github.com/carloluis/react-router-redux/commit/98e22ea48fabc398fae7839043746e0f63893865)

note: simplified example in [codepen](https://codepen.io/carloluis/pen/wePzzP) (using hash history)

**Comment by timdorr** [comment]
Don't create your store in store.js, just export a function that takes a history as an argument and creates the store using it.
