### ISSUE TITLE
react-router-redux@4: Component not rendered after replace/push dispatch

### ISSUE THREAD

**Issue by finom** [reactjs/react-router-redux#582]
I'm getting the issue described at issue title.

```js
<Router
    render={reduxAsyncConnect}
    history={history}
  >
  <Route path="/" component={MainLayout}>
      <IndexRoute component={App} />

      <Route path="login"  component={LoginPage} />
  </Route>
  </Router>
```

Trying to localize the issue I found out that this code works just fine after store initialization:

```js
store.dispatch(replace('/login'))
```

But this doesn't:
```
setTimeout(() => {
     store.dispatch(replace('/login'))
})
```

It redirects but shows no LoginPage component and gives no error. When I open `/login` directly it renders just fine.

**Comment by timdorr** [comment]
It's probably something in your reduxAsyncConnect render method. Without knowing what's in there, I'm not sure what the exact issue is.

**Comment by finom** [comment]
@timdorr that was my first suggestion. The bug appears even when I remove the render prop. Do you have any other Ideas of what I would try to find a reason?

**Comment by mr47** [comment]
@finom solution for RR4 is using not `reduxAsyncConnect` it just don't work with RR4 use `react-jobs`

**Comment by finom** [comment]
@mr47 I use RR3.

**Comment by mr47** [comment]
@finom but issue title is about RR4?

**Comment by mr47** [comment]
@finom yeah you right, its stupid versioning

**Comment by finom** [comment]
@mr47 no it's about react-router-redux@4 and react-router@3
