### ISSUE TITLE
How to know the initial location?

### ISSUE THREAD

**Issue by n-sviridenko** [reactjs/react-router-redux#593]
Hello,

When user changes the location, the store receives the `LOCATION_CHANGE` action. But it happens starting from a second location. How to know when the current user is at the beginning? I know that I can subscribe on history directly, but is it possible to do it using only redux layer? Or maybe there is some way how to extend the `syncHistoryWithStore` function?

```
"react-router": "~3.0.5",
"react-router-redux": "4.0.6",
```

**Comment by timdorr** [comment]
It will sync the initial location. We specifically handle this: https://github.com/reactjs/react-router-redux/blob/master/src/sync.js#L100-L103
