### ISSUE TITLE
Cannot read property 'push' of undefined(…)

### ISSUE THREAD

**Issue by Deviad** [reactjs/react-router-redux#598]
My story is the same as:
https://github.com/reactjs/react-router-redux/issues/425

I open a new thread on this issue because it does not get solved with importing "history" using the @next version of react-router-redux package.
I am using react-router v4

https://stackoverflow.com/questions/45831497/managing-routing-with-react-router-redux-empty-line-on-top-of-the-list-after-ro

Under jayphelps answer you can find my comments with some screenshots.
The weird part is that this stuff is hard to catch. By hard I mean that the browser is fine, just Intellij complains about something being wrong.
However, when you click on the submit button, after the creation of a post nothing else happens.
So you know that something is wrong, but the browser does not catch it.

**Comment by timdorr** [comment]
If you're using React Router 4.0, you you should be using react-router-redux@next (5.0.0-alpha.6). You cannot use the version in this repo with React Router 4.0. 

If things aren't updating when using Redux, see this guide: https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/redux.md
