### ISSUE TITLE
Version 5 redux dev tools support?

### ISSUE THREAD

**Issue by dmitrybelyakov** [reactjs/react-router-redux#599]
Hi,

We are deciding which version of router-redux to use for the upcoming project. We've set up router 4 with redux-router 5 beta6 and it works great, but any changes in dev-tools have no effect whatsoever. We can see the `LOCATION_CHANGE` actions being dispatched, but changing them in dev tools does nothing.

Can you please advise if you will support dev tools any time soon, or if we shall go with the previous version of redux-router?

Thank you!

**Comment by timdorr** [comment]
This is always the case. The actions are swallowed by the middleware. If you change the order of your middleware and devtools application, you should be able to see them.

**Comment by dmitrybelyakov** [comment]
Hey Tim!

Thanks for your suggestion, but it's still a bit unclear - do you maybe have a working example somewhere? We follow the readme on beta6 version and it is still not quite working. Here is how we create our store:
```javascript
const middleware = routerMiddleware(history);
const composeEnhancers = window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__  || compose;
const enhancer = composeEnhancers(applyMiddleware(middleware));
const store = createStore(rootReducer, defaultState, enhancer);
export default store;
```
P.S. Sorry, i know it's not the place for support requests and don't want to be annoying, but we really need to get this thing working or roll back to previous version of router.

**Comment by dmitrybelyakov** [comment]
@timdorr 
Also here's another example, this time not using browser extension, but rather installing devtools into the project: https://github.com/jpsierens/webpack-react-redux (swapping devtools/middleware order didn't not help either)
