### ISSUE TITLE
Documentation should cover connect() and withRouter()

### ISSUE THREAD

**Issue by murph** [reactjs/react-router-redux#600]
Hey,

I added react-router and react-router-redux to my project and had a hard-to-debug issue due to a missing `withRouter` after `connect` on my main App component.

I'm not familiar enough to update the docs, but I think that this should be covered on the `react-router-redux` page.

**Comment by timdorr** [comment]
It does: https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/redux.md

**Comment by murph** [comment]
Maybe those should be linked from the react-router-redux docs?

https://github.com/ReactTraining/react-router/tree/master/packages/react-router-redux
