### ISSUE TITLE
Cannot find module './selectors' from 'index.js'

### ISSUE THREAD

**Issue by thoughtassassin** [reactjs/react-router-redux#607]
All of the sudden my build is breaking. I am seeing this message in the build.

**Comment by thoughtassassin** [comment]
More info:

var _selectors = require('./selectors');

Object.defineProperty(exports, 'getLocation', {
  enumerable: true,
  get: function get() {
    return _selectors.getLocation;
  }
});
Object.defineProperty(exports, 'createMatchSelector', {
  enumerable: true,
  get: function get() {
    return _selectors.createMatchSelector;
  }
});

There is no selectors file in the directory

**Comment by smddzcy** [comment]
Changing `var _selectors = require('./selectors');` to `var _selectors = require('./es/selectors');` fixes the problem.

**Comment by timdorr** [comment]
This isn't the right repo.

**Comment by kajm** [comment]
I tried upgrading from alpha 6 to 7 but got the same problem as @thoughtassassin. After downgrading to alpha 6 it all works fine. I am still  looking for an answer, and I want to go to the right repo if this isnt the right one. @timdorr which is the right repo?

**Comment by smddzcy** [comment]
@timdorr You are not opening the issue in the _right repo_, you are not directing us to the right repo. This is not how you should handle issues.

**Comment by timdorr** [comment]
It's at the top of the readme at the starting page of this repo: https://github.com/reactjs/react-router-redux#were-moving

**Comment by kajm** [comment]
thank you @timdorr  👍
