### ISSUE TITLE
Expose defaultSelectLocationState

### ISSUE THREAD

**Issue by halfzebra** [reactjs/react-router-redux#618]
Hi, I would like to get the default selector from of the library so I could use it my project without creating a custom one.

E.g. v5 comes with [selectors exposed.](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-redux/modules/selectors.js)

Maybe it would make sense to guard against the cases when the property name for router state in Redux is different from the default one `"routing"` by throwing an error like [this one.](https://github.com/reactjs/react-router-redux/blob/master/src/sync.js#L23)

I'm up for making a PR if this makes sense.

**Comment by timdorr** [comment]
Sorry, but I'm not interested in adding that back here. 4.0 is basically complete as-is, and I'd like to keep the dev effort focused on RRR 5.0 and Router 4.0.

**Comment by halfzebra** [comment]
@timdorr no probs, thanks for the reply!
