### ISSUE TITLE
push() replaces url

### ISSUE THREAD

**Issue by anushkadoyan** [reactjs/react-router-redux#628]
I'm trying to use push() to push to the url and update my route. However, push is replacing my url with the specified url in push().

For example:
current url = foo.bar/hello
`push('/world')`
expected url = foo.bar/hello/world
actual url = foo.bar/world

**Comment by timdorr** [comment]
You have to push the full URL. `push('/hello/world')`

**Comment by anushkadoyan** [comment]
Okay, thanks!
