### ISSUE TITLE
LOCATION_CHANGE is wrong action type

### ISSUE THREAD

**Issue by wzup** [reactjs/react-router-redux#633]
You docs:

![reactjs react router redux ruthlessly simple bindings to keep react router and redux in sync](https://user-images.githubusercontent.com/3880497/39821911-fca7358c-53b1-11e8-9304-1800aa12743c.png)

Real action type

![screenshot from 2018-05-09 17-43-26](https://user-images.githubusercontent.com/3880497/39822342-ff105226-53b2-11e8-9a77-8b520faac229.png)

**Comment by timdorr** [comment]
It's an export: https://github.com/reactjs/react-router-redux/blob/master/src/reducer.js#L5
